#' Plot distribution of QC statistics
#'
#' @description
#' This function plots histograms of the various per-read summary statistics
#' calculated by \code{\link{addReadStats}}.
#'
#' @param se A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}},
#'     typically generated by \code{addReadStats}.
#' @param readInfoCol A character scalar providing the name of the column in
#'     \code{colData} that contains read info. Can be \code{NULL} if no such
#'     column exists.
#' @param qcCol A character scalar providing the name of the column in
#'     \code{colData} that contains quality metrics (calculated by
#'     \code{calcReadStats}). Can be \code{NULL} if no such column exists.
#' @param minQscore,maxEntropy,maxFracLowConf,minReadLength,minAlignedLength,minAlignedFraction
#'     Numeric scalars representing possible threshold values used in
#'     \code{\link{filterReads}}, for illustration in the plot panels.
#'
#' @return A \code{ggplot} object.
#'
#' @author Panagiotis Papapasaikas, Charlotte Soneson, Michael Stadler
#'
#' @examples
#' library(SummarizedExperiment)
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                           package = "footprintR")
#' se <- readModBam(bamfile = modbamfiles, regions = "chr1:6940000-6955000",
#'                  modbase = "a", verbose = TRUE,
#'                  BPPARAM = BiocParallel::SerialParam())
#' se <- addReadStats(se, BPPARAM = BiocParallel::SerialParam())
#' plotReadStats(se)
#'
#' @import ggplot2
#' @importFrom tidyr pivot_longer
#' @importFrom tibble rownames_to_column
#' @importFrom BiocGenerics as.data.frame colnames
#' @importFrom SummarizedExperiment colData
#' @importFrom cli cli_abort
#'
#' @export
plotReadStats <- function(se, readInfoCol = "readInfo", qcCol = "QC",
                          minQscore = 0, maxEntropy = Inf,
                          maxFracLowConf = 1, minReadLength = 0,
                          minAlignedLength = 0, minAlignedFraction = 0) {
    # check arguments
    .assertVector(x = se, type = "SummarizedExperiment")
    .assertScalar(x = readInfoCol, type = "character", allowNULL = TRUE,
                  validValues = colnames(colData(se)))
    .assertScalar(x = qcCol, type = "character", allowNULL = TRUE,
                  validValues = colnames(colData(se)))
    .assertScalar(x = minQscore, type = "numeric")
    .assertScalar(x = maxEntropy, type = "numeric")
    .assertScalar(x = maxFracLowConf, type = "numeric", rngIncl = c(0, 1))
    .assertScalar(x = minReadLength, type = "numeric")
    .assertScalar(x = minAlignedLength, type = "numeric")
    .assertScalar(x = minAlignedFraction, type = "numeric", rngIncl = c(0, 1))

    # prepare main plotdata
    dfL <- list()
    # ... from readInfoCol
    if (!is.null(readInfoCol)) {
        tmp <- as.data.frame(se[[readInfoCol]])
        tmp <- tmp[, !grepl("variant_label", colnames(tmp))]
        dfL[[length(dfL) + 1]] <- tmp
    }
    # ... from qcCol
    if (!is.null(qcCol)) {
        tmp <- as.data.frame(se[[qcCol]])
        tmp <- tmp[, !grepl("AC", colnames(tmp))]
        dfL[[length(dfL) + 1]] <- tmp
    }

    if (!all(unlist(lapply(dfL, \(x) identical(x$group_name, dfL[[1]]$group_name))))) {
        cli_abort("names of {.code se${readInfoCol}} and {.code se${qcCol}} are not identical")
    }
    df <- do.call(cbind, lapply(dfL, \(x) x[, !colnames(x) %in% c("group", "group_name")]))
    df$sample <- dfL[[1]]$group_name

    # prepare plotdata for thresholds
    map2thresh <- c(qscore = minQscore, read_length = minReadLength,
                    aligned_length = minAlignedLength,
                    aligned_fraction = minAlignedFraction,
                    MeanConf = maxFracLowConf, SEntrModProb = maxEntropy)
    threshnms <- intersect(names(map2thresh), colnames(df))
    df2 <- data.frame(key = threshnms, value = map2thresh[threshnms])

    # generate plot
    ggplot(pivot_longer(df, names_to = "key",
                        values_to = "value", -sample),
           aes(x = .data$value, fill = .data$sample)) +
        geom_histogram(bins = 32) +
        geom_vline(data = df2, mapping = aes(xintercept = .data$value),
                   linetype = "dashed") +
        facet_wrap(~ key, scales = "free_x") +
        labs(x = NULL,
             y = "Number of reads",
             fill = "Sample") +
        theme_bw()
}
