#' Plot distribution of QC statistics
#'
#' @description
#' This function plots histograms of the various per-read summary statistics
#' calculated by \code{\link{addReadStats}}.
#'
#' @param se A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}},
#'     typically generated by \code{addReadStats}.
#' @param qcCol A character scalar indicating the column in \code{colData(se)}
#'     that contains QC statistics to plot.
#'
#' @return A \code{ggplot} object.
#'
#' @author Panagiotis Papapasaikas, Charlotte Soneson
#'
#' @examples
#' library(SummarizedExperiment)
#' modbamfile <- system.file("extdata", "6mA_1_10reads.bam",
#'                           package = "footprintR")
#' se <- readModBam(bamfile = modbamfile, regions = "chr1:6940000-6955000",
#'            modbase = "a", verbose = TRUE)
#' se <- addReadStats(se)
#' plotReadStats(se)
#'
#' @import ggplot2
#' @importFrom tidyr pivot_longer
#' @importFrom tibble rownames_to_column
#' @importFrom BiocGenerics as.data.frame
#' @importFrom SummarizedExperiment colData
#'
#' @export
plotReadStats <- function(se, qcCol = "QC") {
    .assertVector(x = se, type = "SummarizedExperiment")
    .assertScalar(x = qcCol, type = "character")
    stopifnot(qcCol %in% colnames(SummarizedExperiment::colData(se)))
    
    df <- BiocGenerics::as.data.frame(se[[qcCol]])
    df <- df[, !grepl("AC", colnames(df))]
    df <- df[, !colnames(df) %in% c("group", "group_name")] |>
        tibble::rownames_to_column("sample")

    ggplot(pivot_longer(df, names_to = "key",
                        values_to = "value", -sample),
           aes(x = .data$value, fill = .data$sample)) +
        geom_histogram(bins = 32) +
        facet_wrap(~ key, scales = "free_x") +
        theme_bw()
}
