# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Count frequency of differences between values in integer vectors.
#'
#' @description Given two ascendingly sorted integer vectors \code{query} and
#'     \code{reference}, calculate and count the differences between their
#'     elements that are greater than zero and less than \code{maxd}. The
#'     number of observed distances \code{d} are reported in \code{cnt[d]},
#'     and \code{maxd} corresponds to the \code{length(cnt)}. The function is
#'     called by \code{\link{calcModbaseSpacing}}, which provides a higher level,
#'     more convenient interface.
#'
#' @author Michael Stadler
#'
#' @param query first \code{integer} vector.
#' @param reference second \code{integer} vector. Distances are calculated from
#'     each element in \code{query} to each greater element in
#'     \code{reference}.
#' @param cnt \code{NumericVector} to store the result in. The length of
#'     \code{cnt} defines the maximal distance that will be included in the
#'     analysis, and new counts will be added to the values of \code{cnt}
#'     (repeated calls to \code{calcAndCountDist} will increment existing
#'     counts).
#'
#' @examples
#' cnt <- c(0, 0, 0)
#' calcAndCountDist(c(1, 4, 8), c(2, 3, 4, 5, 8, 9, 10), cnt)
#' cnt
#'
#' @return \code{numeric} vector \code{cnt}, where \code{cnt[d]} correspond to
#'   the number of observed distances \code{d}.
#'
#' @export
calcAndCountDist <- function(query, reference, cnt) {
    .Call(`_footprintR_calcAndCountDist`, query, reference, cnt)
}

#' Calculate footprinting score for a defined footprint and a single read.
#'
#' This function calculates the footprinting scores corresponding to a
#' footprint in the form of a weight vector \code{wgt} for an individual
#' read. The score is based on a cross-correlation of the modification
#' probabilities in \code{pmod} (centered by subtracting \code{0.5}) with
#' \code{wgt}, weighted by the minimum of \code{minweight} and the elements
#' of \code{pmod}.
#'
#' @param pos Integer vector with positions (genomic coordinates) of modified
#'     bases.
#' @param pmod Numeric vector with modification probabilities of modified
#'     bases.
#' @param wgt Numeric vector with weights that define the footprint to score.
#'     Typically centered at zero.
#' @param minconf Numeric scalar giving the minimal confidence of a base to be
#'     included in the calculation.
#' @param minweight Numeric scalar giving the minimal weight for position.
#'
#' @returns
#' A \code{data.frame} with columns \code{pos}, \code{pmod} and \code{score},
#'     in (continuous) base space from \code{min(pos)} to \code{max(pos)}.
#'
#' @noRd
#' @keywords internal
calcFootprintScoreForRead <- function(pos, pmod, wgt, minconf = 0.7, minweight = 0.05) {
    .Call(`_footprintR_calcFootprintScoreForRead`, pos, pmod, wgt, minconf, minweight)
}

filter_modbam_cpp <- function(infile, outfile, modbase, region = ".", includeHeader = TRUE, keepUnmapped = TRUE, keepSecondary = TRUE, keepSupplementary = TRUE, minReadLength = 0L, minAlignedLength = 0L, minAlignedFraction = 0, minQscore = 0.0, minSNR = -1e200, noiseCoefB0 = -1e200, noiseCoefB1 = -1e200, maxFracLowConf = 1.0, maxEntropy = -1.0, LowConf = 0.7, nThreads = 2L, verbose = FALSE) {
    .Call(`_footprintR_filter_modbam_cpp`, infile, outfile, modbase, region, includeHeader, keepUnmapped, keepSecondary, keepSupplementary, minReadLength, minAlignedLength, minAlignedFraction, minQscore, minSNR, noiseCoefB0, noiseCoefB1, maxFracLowConf, maxEntropy, LowConf, nThreads, verbose)
}

#' Create an index for a given bam file
#'
#' The bam file is expected to be already sorted by coordinate and
#' the index file name will be automatically determined by appending
#' \code{.bai} to the bam file name.
#'
#' @param infile A \code{std::string} with the path and name to the input
#'     bam file to be indexed.
#'
#' @returns A \code{std::string} with the name of the created index file.
#'
#'
#' @author Michael Stadler
#'
#' @noRd
#' @keywords internal
index_bam_cpp <- function(infile) {
    .Call(`_footprintR_index_bam_cpp`, infile)
}

#' @title Calculate pairwise distances between read labels
#'
#' @description
#' \code{labelDists} returns all pairwise distances among a set of strings
#'    (read labels) of identical length, consisting of A, C, G, T and -
#'    letters. The distance is in [0, 1] and corresponds to the fraction of
#'    differences in the overlap range, defined as the range excluding the
#'    maximal number of leading and trailing - letters in any of the two
#'    compared labels.
#'
#' @param labels  Character vector of equally sized strings.
#' @param minOverlap An integer scalar giving the minimal number of overlapping
#'     letters. If a pair of labels overlap by less than this number of letters,
#'     their distance is set to the maximal distance (1.0).
#'
#' @return A numeric, symmetric matrix with pairwise distances between the
#'     elements of \code{labels}.
#'
#' @examples
#' labelDists(c("--AACACT-", "---ACCCT-", "---ACAC--"))
#'
#' @noRd
#' @keywords internal
labelDists <- function(labels, minOverlap = 2L) {
    .Call(`_footprintR_labelDists`, labels, minOverlap)
}

#' Constructor for pileup data in bam_pileup_cd*
#'
#' @param data void* (client data)
#' @param b bam1_t* (bam being loaded)
#' @param cd bam_pileup_cd* (client data)
#'
#' @return An integer scalar (zero on success, non-zero on failure)
#'
#' @noRd
#' @keywords internal
NULL

#' Destructor for pileup data in bam_pileup_cd*
#'
#' @param data void* (client data)
#' @param b bam1_t* (bam being loaded)
#' @param cd bam_pileup_cd* (client data)
#'
#' @return An integer scalar (zero)
#'
#' @noRd
#' @keywords internal
NULL

#' Read alignment data for pileup operation
#'
#' @param data void* (client callback data holding alignment file handle)
#' @param b bam1_t* (aligned read)
#'
#' @return same as sam_read1
#'
#' @noRd
#' @keywords internal
NULL

#' Read and pile-up base modifications from a bam file.
#'
#' Parse ML and MM tags (see https://samtools.github.io/hts-specs/SAMtags.pdf,
#' section 1.7) and return a list of information on modified bases.
#'
#' @param inname_str Character scalar with name of the input bam file.
#' @param regions Character vector specifying the region(s) for which
#'     to extract overlapping reads, in the form \code{"chr:start-end"}.
#'     The strings are interpreted by htslib, which understands:
#'     \describe{
#'         \item{"REF" or "REF:"}{: All reads with RNAME REF}
#'         \item{"REF:START"}{: Reads with RNAME REF overlapping START to end of REF}
#'         \item{"REF:-END"}{: Reads with RNAME REF overlapping start of REF to END}
#'         \item{"REF:START-END"}{: Reads with RNAME REF overlapping START to END}
#'         \item{"."}{: All reads from the start of the file}
#'         \item{"*"}{: Unmapped reads at the end of the file (RNAME '*' in SAM)}
#'     }
#' @param modbase Character scalar defining the modified base to extract.
#'     Only modifications corresponding to \code{modbase} and with the
#'     corresponding expected base in the read sequence will be extracted.
#' @param level Character scalar indicating whether to return summary-level or
#'     read-level data. Valid values are "summary" and "read". The read-level
#'     results from \code{pileup_modbam_cpp} correspond to those from
#'     \code{read_modbam_cpp}, but does not contain all annotations currently
#'     returned by the latter.
#' @param mod_prob_thresh Double scalar defining the minimal mod_prob
#'     of a base to be considered modified.
#' @param n_threads Integer scalar defining the number of threads to
#'     use for decompressing a sam record. Especially using in sampling mode
#'     (\code{n_alns_to_sample > 0}), where more time is spend reading and
#'     decompressing bam records than processing them.
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @return A named list with elements \code{"chrom"} (chromosome name),
#'     \code{"ref_position"} (1-based coordinate on \code{"chrom"}),
#'     \code{"ref_mod_strand"} (the strand relative to the reference on which
#'     the modification was identified). If \code{level} is \code{"summary"},
#'     the list additionally contains slots \code{"Nmod"} (number of modified
#'     bases) and \code{"Nvalid"} (number of total bases). If \code{level} is
#'     \code{"read"}, it contains slots \code{"mod_prob"} and \code{"read_id"}.
#'
#' @examples
#' modbamfile <- system.file("extdata", "6mA_1_10reads.bam", package = "footprintR")
#' res <- pileup_modbam_cpp(modbamfile, "chr1", "a", "summary", 0.7, 1, TRUE)
#' str(res)
#'
#' res <- pileup_modbam_cpp(modbamfile, "chr1", "a", "read", 0.7, 1, TRUE)
#' str(res)
#'
#' @seealso https://samtools.github.io/hts-specs/SAMtags.pdf describing the
#'     SAM ML and MM tags for base modifications.
#'     Helpful examples are available in
#'      https://github.com/samtools/htslib/blob/develop/samples/pileup_mod.c
#'
#' @author Michael Stadler, Charlotte Soneson
#'
#' @importFrom cli cli_progress_step cli_progress_done
#'
#' @noRd
#' @keywords internal
pileup_modbam_cpp <- function(inname_str, regions, modbase, level = "summary", mod_prob_thresh = 0.5, n_threads = 2L, verbose = FALSE) {
    .Call(`_footprintR_pileup_modbam_cpp`, inname_str, regions, modbase, level, mod_prob_thresh, n_threads, verbose)
}

#' Read base modifications from a bam file.
#'
#' Parse ML and MM tags (see https://samtools.github.io/hts-specs/SAMtags.pdf,
#' section 1.7) and return a list of information on modified bases. The
#' function implements three distinct reading modes:
#' \enumerate{
#'     \item{Extraction of modification probabilities for
#'         alignments overlapping provided regions. This mode is selected
#'         if \code{n_alns_to_sample = 0} and \code{windowSize = 0}.}
#'     \item{Extraction of modification probabilities for alignments
#'         randomly sampled from provided chromosomes. This is selected
#'         if \code{n_alns_to_sample > 0} and \code{windowSize = 0}.}
#'     \item{Counting of pairs of bases by distance and modification state.
#'         This mode is selected if \code{windowSize > 0}.}
#' }
#'
#' @param inname_str Character scalar with name of the input bam file.
#' @param regions Character vector specifying the region(s) for which
#'     to extract overlapping reads, in the form \code{"chr:start-end"}
#' @param modbase Character scalar defining the modified base to extract.
#' @param n_alns_to_sample Integer defining the number of alignments
#'     to randomly sample.
#' @param tnames_for_sampling String vector with target names (chromosomes)
#'     from which to sample \code{n_alns_to_sample} alignments. Ignored if
#'     \code{n_alns_to_sample = 0}.
#' @param variantRefNames Character vector with target names (chromosomes)
#'     of single nucleotide variants.
#' @param variantRefPositions Integer vector with 0-based target positions
#'     of single nucleotide variants. Expected to have identical length and
#'     to be parallel to \code{variantRefNames}.
#' @param threshUnmod Numeric scalar giving the maximal (non-inclusive)
#'     modification probability threshold for an unmodified base.
#' @param threshMod Numeric scalar giving the minimal modification probability
#'     threshold for a modified base.
#' @param windowSize Numeric scalar giving the maximum window size
#'     covering pairs of modified bases to consider in pair-counting mode.
#'     A window size of 1 corresponds to a single base, a size of 2 to
#'     directly adjacent bases, etc.
#' @param minMapQ Numeric scalar giving the minimal mapping quality to include
#'     alignments in pair-counting mode.
#' @param minAlignedLength Numeric scalar giving the minimal alignment length
#'     to include alignments in pair-counting mode.
#' @param n_threads Integer scalar defining the number of threads to
#'     use for decompressing a sam record. Especially using in sampling mode
#'     (\code{n_alns_to_sample > 0}), where more time is spend reading and
#'     decompressing bam records than processing them.
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @return For reading modes 1. and 2., a named list with elements \code{"read_id"},
#'     \code{"forward_read_position"}, \code{"ref_position"},
#'     \code{"chrom"}, \code{"ref_mod_strand"}, \code{"call_code"},
#'     \code{"canonical_base"}, \code{"mod_prob"} and \code{"read_df"}.
#'     The meaning of these elements is described in https://nanoporetech.github.io/modkit/intro_extract.html,
#'     apart from \code{"mod_prob"}, which is equal to \code{call_prob} for
#'     modified bases and equal to \code{1 - call_prob} for unmodified bases
#'     (\code{call_code == "-"}), and \code{"read_df"}, which is a
#'      \code{data.frame} with one row per read and columns \code{"read_id"}
#'     (the read identifier), \code{"qscore"} (the read quality score recorded
#'     in the \code{qs} tag of each bam record), \code{"read_length"} (the
#'     total read length), and \code{"aligned_length"} (the number of
#'     aligned bases), and \code{"ref_position"}, which is 0-based in
#'     the output of \code{modkit extract}, but 1-based here.
#'     For reading mode 3., a named list with a single element called
#'     \code{"pair_counts"}, corresponding to a \code{windowSize}-by-4
#'     matrix with the numbers of pairs of bases at a given distance (row) and
#'     in a given state (columns: 00, 01, 10 and 11).
#'
#' @examples
#' modbamfile <- system.file("extdata", "6mA_1_10reads.bam", package = "footprintR")
#' res1 <- read_modbam_cpp(inname_str = modbamfile,
#'                         regions = "chr1:6940000-6955000",
#'                         modbase = "a",
#'                         n_alns_to_sample = 0,
#'                         tnames_for_sampling = "",
#'                         variantRefNames = "",
#'                         variantRefPositions = 0,
#'                         n_threads = 1,
#'                         verbose = TRUE)
#' str(res1)
#'
#' res3 <- read_modbam_cpp(inname_str = modbamfile,
#'                         regions = "chr1:6940000-6955000",
#'                         modbase = "a",
#'                         n_alns_to_sample = 0,
#'                         tnames_for_sampling = "",
#'                         variantRefNames = "",
#'                         variantRefPositions = 0,
#'                         windowSize = 200,
#'                         n_threads = 1,
#'                         verbose = TRUE)
#' head(res3$pair_counts)
#'
#' @seealso https://samtools.github.io/hts-specs/SAMtags.pdf describing the
#'     SAM ML and MM tags for base modifications.
#'     Helpful examples are available in
#'      https://github.com/samtools/htslib/blob/develop/samples/modstate.c
#'     Documentation of the htslib C API is available in
#'      https://github.com/samtools/htslib/blob/develop/htslib/sam.h
#'     Description of returned values
#'      https://nanoporetech.github.io/modkit/intro_extract.html
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @importFrom cli cli_progress_step cli_progress_done cli_alert_info
#'
#' @noRd
#' @keywords internal
read_modbam_cpp <- function(inname_str, regions, modbase, n_alns_to_sample, tnames_for_sampling, variantRefNames, variantRefPositions, threshUnmod = 0.5, threshMod = 0.5, windowSize = 0L, minMapQ = 0L, minAlignedLength = 0L, n_threads = 2L, verbose = FALSE) {
    .Call(`_footprintR_read_modbam_cpp`, inname_str, regions, modbase, n_alns_to_sample, tnames_for_sampling, variantRefNames, variantRefPositions, threshUnmod, threshMod, windowSize, minMapQ, minAlignedLength, n_threads, verbose)
}

#' @title Sample Entropy of Time series signal
#'
#' @description
#' \code{sampleEntropy} returns the sample entropy of a time-series signal
#' see also https://en.wikipedia.org/wiki/Sample_entropy
#'
#' @details
#' This function calculates the Sample Entropy of a time-series vector
#' given as argument. Sample Entropy is  used to assess the complexity of physiological
#' time-series signals.
#' This C++  implementation is a modified version of:
#' https://gist.github.com/schochastics/e3684645763e93cbc2ed7d1b70ee5fe6
#'
#' @param data  Numeric vector
#' @param m  Integer, the embedding dimension, as for chaotic time series; a preferred value is 2.
#' @param r  Scaling parameter for the filtering factor. The filtering factor is r x standard deviation of the signal
#'
#' @return The Sample Entropy value of the time-series signal
#'
#' @examples
#' ts <- runif(100,0,1)
#' sampleEntropy(ts, m=2L, r=0.2)
#'
#' @seealso [wikipedia:Sample_entropy](https://en.wikipedia.org/wiki/Sample_entropy)
#' [Multiscale entropy of biological signals](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.71.021906)
#'
#' @noRd
#' @keywords internal
sampleEntropy <- function(data, m, r) {
    .Call(`_footprintR_sampleEntropy`, data, m, r)
}

concatenate_files <- function(input_files, output_file) {
    .Call(`_footprintR_concatenate_files`, input_files, output_file)
}

concatenate_hts_files <- function(input_files, output_file, ncpu = 4L) {
    .Call(`_footprintR_concatenate_hts_files`, input_files, output_file, ncpu)
}

getChromosomeNamesFromBam <- function(bamfile) {
    .Call(`_footprintR_getChromosomeNamesFromBam`, bamfile)
}

get_unmodified_base <- function(b) {
    .Call(`_footprintR_get_unmodified_base`, b)
}

complement <- function(n) {
    .Call(`_footprintR_complement`, n)
}

