# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

complement <- function(n) {
    .Call(`_footprintR_complement`, n)
}

get_unmodified_base <- function(b) {
    .Call(`_footprintR_get_unmodified_base`, b)
}

#' Read base modifications from a bam file.
#'
#' Parse ML and MM tags (see https://samtools.github.io/hts-specs/SAMtags.pdf,
#' section 1.7) and return a list of information on modified bases.
#'
#' @param inname_str Character scalar with name of the input bam file.
#' @param regions Character vector specifying the region(s) for which
#'     to extract overlapping reads, in the form \code{"chr:start-end"}
#' @param modbase Character scalar defining the modified base to extract.
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @return A named list with elements \code{"read_id"},
#'     \code{"forward_read_position"}, \code{"ref_position"},
#'     \code{"chrom"}, \code{"ref_strand"}, \code{"call_code"},
#'     \code{"canonical_base"} and \code{"mod_prob"}. The meaning of these
#'     elements is described in https://nanoporetech.github.io/modkit/intro_extract.html,
#'     apart from \code{"mod_prob"}, which is equal to \code{call_prob} for
#'     modified bases and equal to \code{1 - call_prob} for unmodified bases
#'     (\code{call_code == "-"}).
#'
#' @examples
#' modbamfile <- system.file("extdata", "6mA_1_10reads.bam",
#'                           package = "footprintR")
#' res <- read_modbam_cpp(modbamfile, "chr1:6940000-6955000", "a", TRUE)
#' str(res)
#'
#' @seealso https://samtools.github.io/hts-specs/SAMtags.pdf describing the
#'     SAM ML and MM tags for base modifications.
#'     Helpful examples are available in
#'      https://github.com/samtools/htslib/blob/develop/samples/modstate.c
#'     Documentation of the htslib C API is available in
#'      https://github.com/samtools/htslib/blob/develop/htslib/sam.h
#'     Description of returned values
#'      https://nanoporetech.github.io/modkit/intro_extract.html
#'
#' @author Michael Stadler
#'
#' @noRd
#' @keywords internal
read_modbam_cpp <- function(inname_str, regions, modbase, verbose = FALSE) {
    .Call(`_footprintR_read_modbam_cpp`, inname_str, regions, modbase, verbose)
}

#' @title Sample Entropy of Time series signal
#'
#' @description
#' \code{sampleEntropy} returns the sample entropy of a time-series signal
#' see also https://en.wikipedia.org/wiki/Sample_entropy
#'
#' @details
#' This function calculates the Sample Entropy of a time-series vector
#' given as argument. Sample Entropy is  used to assess the complexity of physiological
#' time-series signals.
#' This C++  implementation is a modified version of:
#' https://gist.github.com/schochastics/e3684645763e93cbc2ed7d1b70ee5fe6 
#'
#' @param data  Numeric vector 
#' @param m  Integer, the embedding dimension, as for chaotic time series; a preferred value is 2.
#' @param r  Scaling parameter for the filtering factor. The filtering factor is r x standard deviation of the signal 
#'
#' @return The Sample Entropy value of the time-series signal
#'
#' @examples
#' ts <- runif(100,0,1)
#' sampleEntropy(ts, m=2L, r=0.2)
#' 
#' @seealso [wikipedia:Sample_entropy](https://en.wikipedia.org/wiki/Sample_entropy)
#' [Multiscale entropy of biological signals](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.71.021906)
#' 
sampleEntropy <- function(data, m, r) {
    .Call(`_footprintR_sampleEntropy`, data, m, r)
}

