#' Read collapsed single-molecule footprinting data from a `bedMethyl` file
#'
#' @description
#' This function will read collapsed single-molecule footprinting data
#' (reads combined per genomic position) from a \code{bedMethyl} file.
#'
#' @param fnames Character vector with one or several paths of \code{bedMethyl}
#'     files, such as generated by \code{modkit pileup}. Each file will be read
#'     separately and become one of the columns in the returned
#'     \code{\link[SummarizedExperiment]{SummarizedExperiment}} object.
#'     If \code{fnames} is a named vector, the names are used as column names in
#'     the returned object. Otherwise, the column names will be \code{s1}, ...,
#'     \code{sN}, where \code{N} is the length of \code{fnames}.
#'     If several elements of \code{fnames} have identical
#'     names, the data from the corresponding files are summed into a single
#'     column in the returned object.
#' @param modbase Character vector defining the modified base for each sample.
#'     If \code{modbase} is a named vector, the names should correspond to
#'     the names of \code{fnames}. Otherwise, it will be assumed that the
#'     elements are in the same order as the files in \code{fnames}. If
#'     \code{modbase} has length 1, the same modified base will be used for
#'     all samples.
#' @param nrows Only read \code{nrows} rows of the input file.
#' @param sampleAnnot A \code{data.frame} (or \code{NULL}) providing annotations
#'     for the samples. It must contain at least one column, named
#'     \code{"sample"}, which must contain all the values of
#'     \code{names(fnames)}. The provided annotations will be propagated to
#'     the returned \code{SummarizedExperiment} object.
#' @param seqinfo \code{NULL} or a \code{\link[GenomeInfoDb]{Seqinfo}} object
#'     containing information about the set of genomic sequences (chromosomes).
#'     Alternatively, a named numeric vector with genomic sequence names and
#'     lengths. Useful to set the sorting order of sequence names.
#' @param sequenceContextWidth,sequenceReference Define the sequence
#'     context to be extracted around modified bases. By default (
#'     \code{sequenceContextWidth = 0}), no sequence context will be
#'     extracted, otherwise it will be returned in \code{rowData(x)$sequenceContext}.
#'     See \code{\link{addSeqContext}} for details.
#' @param BPPARAM A \code{\link[BiocParallel]{BiocParallelParam}} object that
#'     controls the number of parallel CPU threads to use for some of the steps
#'     in \code{readBedMethyl()}. The default value is
#'     (\code{\link[BiocParallel]{MulticoreParam}(4L, RNGseed = 42L)})
#' @param verbose If \code{TRUE}, report on progress.
#'
#' @return A \code{\link[SummarizedExperiment]{SummarizedExperiment}} object
#'     with genomic positions in rows and samples (the unique names of
#'     \code{fnames}) in the columns. If \code{sequenceContextWidth != 0},
#'     \code{rowData(x)$sequenceContext} will be a \code{\link[Biostrings]{DNAStringSet}}
#'     object with the extracted sequences.
#'
#' @author Michael Stadler, Charlotte Soneson
#'
#' @examples
#' bmfile <- system.file("extdata", "modkit_pileup_1.bed.gz",
#'                       package = "footprintR")
#' readBedMethyl(bmfile, modbase = "m",
#'               BPPARAM = BiocParallel::SerialParam())
#'
#' @seealso [`modkit` software](https://nanoporetech.github.io/modkit),
#'     [`bedMethyl` format description](https://nanoporetech.github.io/modkit/intro_bedmethyl.html#description-of-bedmethyl-output),
#'     \code{\link[SummarizedExperiment]{SummarizedExperiment}} for the returned object type,
#'     \code{\link[data.table]{fread}} for the function used to read the input files,
#'     \code{\link{addSeqContext}} used to add the sequence context.
#'
#' @import SummarizedExperiment
#' @importFrom data.table fread
#' @importFrom GenomicRanges GPos match resize trim
#' @importFrom GenomeInfoDb seqlengths seqlengths<-
#' @importFrom S4Vectors mcols mcols<- DataFrame
#' @importFrom Biostrings readDNAStringSet DNAStringSet
#' @importFrom BSgenome getSeq
#' @importFrom BiocGenerics sort
#' @importFrom methods as is
#' @importFrom BiocParallel bplapply MulticoreParam bpnworkers
#'
#' @export
readBedMethyl <- function(fnames,
                          modbase,
                          nrows = Inf,
                          sampleAnnot = NULL,
                          seqinfo = NULL,
                          sequenceContextWidth = 0,
                          sequenceReference = NULL,
                          BPPARAM = MulticoreParam(4L, RNGseed = 42L),
                          verbose = FALSE) {
    # digest arguments
    .assertVector(x = fnames, type = "character")
    if (any(i <- !file.exists(fnames))) {
        stop("not all `fnames` exist: ", paste(fnames[i], collapse = ", "))
    }
    if (is.null(names(fnames))) {
        names(fnames) <- paste0("s", seq_along(fnames))
    }
    .assertVector(x = sampleAnnot, type = "data.frame", allowNULL = TRUE)
    if (!is.null(sampleAnnot)) {
        if (!("sample" %in% colnames(sampleAnnot))) {
            stop("sampleAnnot must have at least a column named 'sample'")
        }
        if (!all(names(fnames) %in% sampleAnnot$sample)) {
            stop("Annotation information missing for some samples: ",
                 paste(setdiff(names(fnames), sampleAnnot$sample),
                       collapse = ", "))
        }
    }
    if (length(modbase) == 1) {
        modbase <- rep(modbase, length(fnames))
    }
    .assertVector(x = modbase, type = "character", len = length(fnames))
    if (is.null(names(modbase))) {
        names(modbase) <- names(fnames)
    } else {
        if (!all(names(modbase) %in% names(fnames))) {
            stop("names of `modbase` and `fnames` don't agree")
        }
    }
    # for valid values of `modbase`, see
    # https://samtools.github.io/hts-specs/SAMtags.pdf (section 1.7)
    if (any(i <- !modbase %in% c("m","h","f","c","C","g","e","b","T",
                                 "U","a","A","o","G","n","N"))) {
        stop("invalid `modbase` values: ",
             paste(unique(modbase[i]), collapse = ", "))
    }
    if (any(lengths(lapply(split(modbase, names(modbase)), unique)) != 1L)) {
        stop("at least one sample was defined to have more than one modbase")
    }
    .assertScalar(x = nrows, type = "numeric", rngIncl = c(1, Inf))
    if (!is.null(seqinfo)) {
        if (!is(seqinfo, "Seqinfo") &&
            (!is.numeric(seqinfo) || is.null(names(seqinfo)))) {
            stop("`seqinfo` must be `NULL`, a `Seqinfo` object or a named",
                 " numeric vector with genomic sequence lengths.")
        }
    }
    .assertScalar(x = sequenceContextWidth, type = "numeric", rngIncl = c(0, 1000))
    .assertVector(x = BPPARAM, type = "BiocParallelParam")
    .assertScalar(x = verbose, type = "logical")
    if (any(grepl("[.](gz|bz2)$", fnames))) {
        .assertPackagesAvailable("R.utils")
    }

    # get sample names
    nms <- unique(names(fnames))

    # load data
    .message("reading input files")
    dfL <- lapply(fnames, function(fname) {
        .message("    {.file fname}")
        fread(file = fname, sep = "\t", nrows = nrows, header = FALSE,
              nThread = bpnworkers(BPPARAM), data.table = FALSE, verbose = FALSE,
              col.names = c("chr", "modbase", "strand", "start", "N_valid", "N_mod"),
              select = list(character = c(1, 4, 6), integer = c(2, 10, 12)))
    })

    # filter by `modbase`
    if (!is.null(modbase)) {
        .message("filtering modifications (retaining {modbase})")
        dfL <- bplapply(dfL, function(df, mymodbase = modbase) {
            df[df$modbase %in% mymodbase, ]
        }, BPPARAM = BPPARAM)
    }

    # create GPos objects for each input
    # (convert 0-based start from bed format to 1-based start in GenomicRanges)
    gposL <- bplapply(dfL, function(df, myseqinfo = seqinfo) {
        GenomicRanges::GPos(seqnames = df$chr, pos = df$start + 1L,
                            strand = df$strand, seqinfo = myseqinfo)
    }, BPPARAM = BPPARAM)

    # create combined GPos
    if (length(dfL) > 1) {
        .message("finding unique genomic positions...")
        gpos <- sort(sort(unique(do.call(c, unname(gposL)))), ignore.strand = TRUE)
        .message("collapsed {sum(lengths(gposL))} position{?s} to {length(gpos)} unique one{?s}")
    } else {
        gpos <- sort(sort(gposL[[1]]), ignore.strand = TRUE)
    }

    # add sequence context
    if (sequenceContextWidth > 0) {
        .message("extracting sequence contexts")
        mcols(gpos)$sequenceContext <- extractSeqContext(
            x = as(gpos, "GRanges"),
            sequenceContextWidth = sequenceContextWidth,
            sequenceReference = sequenceReference)
    }

    # create assays
    nmod <- nval <- matrix(data = 0, nrow = length(gpos), ncol = length(nms),
                           dimnames = list(NULL, nms))
    for (i in seq_along(dfL)) {
        i_row <- match(gposL[[i]], gpos)
        i_col <- match(names(dfL)[i], nms)
        nmod[i_row, i_col] <- nmod[i_row, i_col] + dfL[[i]]$N_mod
        nval[i_row, i_col] <- nval[i_row, i_col] + dfL[[i]]$N_valid
    }

    # create summarized experiment
    cdata <- DataFrame(
        row.names = nms,
        sample = nms,
        modbase = modbase[nms]
    )
    if (!is.null(sampleAnnot) && any(colnames(sampleAnnot) != "sample")) {
        sampleAnnot <- sampleAnnot[match(cdata$sample, sampleAnnot$sample),
                                   colnames(sampleAnnot) != "sample",
                                   drop = FALSE]
        cdata <- cbind(cdata, sampleAnnot)
    }
    stopifnot(colnames(nmod) == cdata$sample,
              colnames(nval) == cdata$sample)
    se <- SummarizedExperiment(
        assays = list(Nmod = nmod, Nvalid = nval),
        rowRanges = gpos,
        colData = cdata,
        metadata = list(readLevelData = list(assayNames = character(0),
                                             colDataColumns = character(0))))

    # return
    return(se)
}
