#' Read modkit extract file(s)
#'
#' @description
#' This function reads one or more modkit extract files and generates a
#' single SummarizedExperiment object with rows representing positions and
#' columns representing samples. The SummarizedExperiment object
#' contains one assay (\code{mod_prob}) with modification probabilities for
#' each position in each read. Unobserved read/position combinations are
#' represented by \code{NA}.
#'
#' @param fnames Character vector with one or several paths of \code{extract.tsv}
#'     files, such as generated by \code{modkit}. If \code{fnames} is a named
#'     vector, the names are used as prefixes for the column (read) names in
#'     the returned \code{SummarizedExperiment} object, and as column names
#'     for the object itself. Otherwise, the prefixes/names
#'     will be \code{s1}, ..., \code{sN}, where \code{N} is the length of
#'     \code{fnames}.
#' @param modbase Character vector defining the modified base for each sample.
#'     If \code{modbase} is a named vector, the names should correspond to
#'     the names of \code{fnames}. Otherwise, it will be assumed that the
#'     elements are in the same order as the files in \code{fnames}. If
#'     \code{modbase} has length 1, the same modified base will be used for
#'     all samples.
#' @param filter Either \code{NULL} (no filtering is performed),
#'     \code{"modkit"} (only records where the \code{"fail"} column in the
#'     extract file is \code{FALSE} are retained), or a named vector, providing
#'     filter thresholds (on the call probability) for the
#'     unmodified and modified bases, respectively. The names of the vector
#'     should be \code{"-"} and the value(s) in \code{modbase}.
#' @param nrows Only read \code{nrows} rows of each input file.
#' @param sampleAnnot A \code{data.frame} (or \code{NULL}) providing annotations
#'     for the samples. It must contain at least one column, named
#'     \code{"sample"}, which must contain all the values of
#'     \code{names(fnames)}. The provided annotations will be propagated to
#'     the returned \code{SummarizedExperiment} object.
#' @param seqinfo \code{NULL} or a \code{\link[GenomeInfoDb]{Seqinfo}} object
#'     containing information about the set of genomic sequences (chromosomes).
#'     Alternatively, a named numeric vector with genomic sequence names and
#'     lengths. Useful to set the sorting order of sequence names.
#' @param sequenceContextWidth,sequenceReference Define the sequence
#'     context to be extracted around modified bases. By default (
#'     \code{sequenceContextWidth = 0}), no sequence context will be
#'     extracted, otherwise it will be returned in \code{rowData(x)$sequenceContext}.
#'     See \code{\link{addSeqContext}} for details.
#' @param BPPARAM A \code{\link[BiocParallel]{BiocParallelParam}} object that
#'     controls the number of parallel CPU threads to use for some of the steps
#'     in \code{readModkitExtract()}. The default value is
#'     (\code{\link[BiocParallel]{MulticoreParam}(4L, RNGseed = 42L)}).
#' @param verbose If \code{TRUE}, report on progress.
#'
#' @return A \code{\link[SummarizedExperiment]{SummarizedExperiment}} object
#'     with genomic positions in rows and samples in columns. The assay
#'     \code{"mod_prob"} contains per-read modification probabilities,
#'     with each column (sample) corresponding to a position-by-read
#'     \code{\link[SparseArray]{NaMatrix}}.
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @examples
#' extrfile <- system.file("extdata", "modkit_extract_rc_5mC_1.tsv.gz",
#'                         package = "footprintR")
#' ## ... no filtering
#' readModkitExtract(extrfile, modbase = "m", filter = NULL,
#'                   BPPARAM = BiocParallel::SerialParam())
#' ## ... modkit filtering
#' readModkitExtract(extrfile, modbase = "m", filter = "modkit",
#'                   BPPARAM = BiocParallel::SerialParam())
#'
#' @seealso [`modkit` software](https://nanoporetech.github.io/modkit),
#'     \code{\link[SummarizedExperiment]{SummarizedExperiment}} for the returned object type,
#'     \code{\link[data.table]{fread}} for the function used to read the input files
#'
#' @importFrom SummarizedExperiment SummarizedExperiment colData rowRanges
#' @importFrom data.table fread
#' @importFrom BiocParallel bplapply MulticoreParam bpnworkers
#' @importFrom GenomicRanges GPos match
#' @importFrom S4Vectors make_zero_col_DFrame DataFrame
#' @importFrom SparseArray NaArray
#' @importFrom BiocGenerics pos strand do.call cbind sort
#' @importFrom GenomeInfoDb seqnames
#' @importFrom cli cli_abort
#'
#' @export
readModkitExtract <- function(fnames,
                              modbase,
                              filter = NULL,
                              nrows = Inf,
                              sampleAnnot = NULL,
                              seqinfo = NULL,
                              sequenceContextWidth = 0,
                              sequenceReference = NULL,
                              BPPARAM = MulticoreParam(4L, RNGseed = 42L),
                              verbose = FALSE) {

    # digest arguments
    .assertVector(x = fnames, type = "character")
    if (any(i <- !file.exists(fnames))) {
        cli_abort("not all {.arg fnames} exist: {.file {fnames[i]}}")
    }
    if (is.null(names(fnames))) {
        names(fnames) <- paste0("s", seq_along(fnames))
    } else if (any(duplicated(names(fnames)))) {
        cli_abort("{.code names(fnames)} are not unique")
    }
    .assertVector(x = sampleAnnot, type = "data.frame", allowNULL = TRUE)
    if (!is.null(sampleAnnot)) {
        if (!("sample" %in% colnames(sampleAnnot))) {
            cli_abort("{.arg sampleAnnot} must have at least a column named 'sample'")
        }
        if (!all(names(fnames) %in% sampleAnnot$sample)) {
            cli_abort(paste0(
                "Annotation information missing for some samples: ",
                "{setdiff(names(fnames), sampleAnnot$sample)}"))
        }
    }
    if (length(modbase) == 1) {
        modbase <- rep(modbase, length(fnames))
    }
    .assertVector(x = modbase, type = "character", len = length(fnames))
    if (is.null(names(modbase))) {
        names(modbase) <- names(fnames)
    } else {
        if (!all(names(modbase) %in% names(fnames))) {
            cli_abort("names of {.arg modbase} and {.arg fnames} don't agree")
        }
    }
    # for valid values of `modbase`, see
    # https://samtools.github.io/hts-specs/SAMtags.pdf (section 1.7)
    if (any(i <- !modbase %in% c("m","h","f","c","C","g","e","b","T",
                                 "U","a","A","o","G","n","N"))) {
        cli_abort("invalid {.arg modbase} values: {unique(modbase[i])}")
    }
    if (!is.null(filter)) {
        if (is.character(filter)) {
            .assertScalar(x = filter, type = "character", validValues = "modkit")
        } else {
            .assertVector(x = filter, type = "numeric", rngIncl = c(0, 1))
            if (is.null(names(filter))) {
                cli_abort("{.arg filter} must be a named vector")
            }
            if (any(i <- !(unique(c("-", modbase))) %in% names(filter))) {
                cli_abort(paste0(
                    "a filter threshold needs to be supplied for all ",
                    "modified bases, not present for: {unique(c('-', modbase))[i]}"))
            }
        }
    }
    .assertScalar(x = nrows, type = "numeric", rngIncl = c(1, Inf))
    if (!is.null(seqinfo)) {
        if (!is(seqinfo, "Seqinfo") &&
            (!is.numeric(seqinfo) || is.null(names(seqinfo)))) {
            cli_abort(paste0(
                "{.arg seqinfo} must be {.code NULL}, a {.cls Seqinfo} object ",
                "or a named {.cls numeric} vector with genomic sequence lengths."))
        }
    }
    .assertScalar(x = sequenceContextWidth, type = "numeric", rngIncl = c(0, 1000))
    .assertVector(x = BPPARAM, type = "BiocParallelParam")
    .assertScalar(x = verbose, type = "logical")
    if (any(grepl("[.](gz|bz2)$", fnames))) {
        .assertPackagesAvailable("R.utils")
    }

    # load data
    .message("reading input {length(fnames)} file{?s}")
    # pre-allocate lists for data and filter thresholds
    dfL <- vector("list", length = length(fnames))
    modkit_threshold <- vector("list", length = length(fnames))
    filter_threshold <- vector("list", length = length(fnames))
    names(dfL) <- names(modkit_threshold) <-
        names(filter_threshold) <- names(fnames)
    for (nm in names(fnames)) {
        .message("    {.file {fnames[nm]}}")
        # read data
        tmp <- fread(
            file = fnames[nm], sep = "\t", nrows = nrows, header = TRUE,
            nThread = bpnworkers(BPPARAM), data.table = FALSE, verbose = FALSE,
            select = list(character = c("chrom", "call_code", "read_id", "ref_strand"),
                          integer = c("ref_position"),
                          logical = c("fail"),
                          numeric = c("call_prob")))
        # keep only rows corresponding to specified modbase or '-'
        tmp <- tmp[tmp$call_code %in% c(modbase[nm], "-"), ]
        # calculate modification probability
        tmp$mod_prob <- ifelse(tmp$call_code == modbase[nm], tmp$call_prob,
                               1 - tmp$call_prob)
        # record filter threshold implied by modkit
        mod_fail_idx <- which(tmp$fail & tmp$call_code == modbase[nm])
        unmod_fail_idx <- which(tmp$fail & tmp$call_code == "-")
        modkit_threshold[[nm]] <- structure(
            c(ifelse(length(mod_fail_idx) > 0,
                     max(tmp$call_prob[mod_fail_idx]), -Inf),
              ifelse(length(unmod_fail_idx) > 0,
                     max(tmp$call_prob[unmod_fail_idx]), -Inf)),
            names = c(modbase[nm], "-")
        )
        # filter
        if (!is.null(filter)) {
            if (is.character(filter) && filter == "modkit") {
                tmp <- tmp[!tmp$fail, ]
                filter_threshold[[nm]] <- modkit_threshold[[nm]]
            } else if (is.numeric(filter)) {
                tmp <- tmp[(tmp$call_code == "-" & tmp$call_prob > filter["-"]) |
                               (tmp$call_code == modbase[nm] &
                                    tmp$call_prob > filter[modbase[nm]]), ]
                filter_threshold[[nm]] <- filter
            }
        }
        # convert to 1-based positions
        tmp$ref_position <- tmp$ref_position + 1
        dfL[[nm]] <- tmp
    }

    # create GPos objects for each input
    gposL <- bplapply(dfL, function(df, myseqinfo = seqinfo) {
        GenomicRanges::GPos(seqnames = df$chrom, pos = df$ref_position,
                            strand = df$ref_strand, seqinfo = myseqinfo)
    }, BPPARAM = BPPARAM)

    # create combined GPos, reduce to unique positions
    .message("finding unique genomic positions...")
    gpos <- sort(sort(unique(do.call(c, unname(gposL)))), ignore.strand = TRUE)
    .message("collapsed {sum(lengths(gposL))} positions to {length(gpos)} unique ones")

    # add sequence context
    if (sequenceContextWidth > 0) {
        .message("extracting sequence contexts")
        mcols(gpos)$sequenceContext <- extractSeqContext(
            x = as(gpos, "GRanges"),
            sequenceContextWidth = sequenceContextWidth,
            sequenceReference = sequenceReference)
    }

    # extract read names
    readL <- lapply(dfL, function(df) unique(df$read_id))

    # modified probability
    modmat <- make_zero_col_DFrame(nrow = length(gpos))
    for (nm in names(fnames)) {
        x <- dfL[[nm]]
        namat <- NaArray(dim = c(length(gpos), length(readL[[nm]])),
                         dimnames = list(NULL, paste0(nm, "-", readL[[nm]])),
                         type = "double")
        i <- match(gposL[[nm]], gpos)
        j <- match(x$read_id, readL[[nm]])
        namat[cbind(i, j)] <- x$mod_prob
        modmat[[nm]] <- namat
    }

    # create SummarizedExperiment object
    cdata <- DataFrame(
        row.names = names(modmat),
        sample = names(modmat),
        modbase = modbase[names(modmat)]
    )
    if (!is.null(sampleAnnot) && any(colnames(sampleAnnot) != "sample")) {
        sampleAnnot <- sampleAnnot[match(cdata$sample, sampleAnnot$sample),
                                   colnames(sampleAnnot) != "sample",
                                   drop = FALSE]
        cdata <- cbind(cdata, sampleAnnot)
    }
    stopifnot(names(modmat) == cdata$sample)
    se <- SummarizedExperiment(
        assays = list(mod_prob = modmat),
        rowRanges = gpos,
        colData = cdata,
        metadata = list(modkit_threshold = modkit_threshold,
                        filter_threshold = filter_threshold,
                        readLevelData = list(assayNames = "mod_prob",
                                             colDataColumns = character(0)))
    )
    rownames(se) <- paste0(
        seqnames(rowRanges(se)), ":", pos(rowRanges(se)), ":",
        strand(rowRanges(se)))
    colnames(se) <- rownames(colData(se))

    se
}
