#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges IRanges
#' @keywords internal
#' @noRd
.tileChromosome <- function(tileSize,
                            windowSize,
                            windowStep,
                            chromName,
                            chromLength) {
    # tile a chromosome
    nWindowsPerTile <- floor(tileSize / windowStep)
    tileSize <- ((nWindowsPerTile - 1) * windowStep) + windowSize
    nTiles <- ceiling((chromLength - (windowSize - windowStep)) / (tileSize - (windowSize - windowStep)))
    s <- 1 + (seq.int(nTiles) - 1) * (tileSize - windowSize + windowStep)
    regs <- GRanges(chromName, IRanges(start = s, width = tileSize))
    regs
}

#' Calculate directed p-value from chi-square test
#'
#' @keywords internal
#' @noRd
#' @importFrom stats chisq.test
.calcDirChiSqP <- function(Nmodpos, Nmodneg, Nvalidpos, Nvalidneg) {
    if (Nvalidpos + Nvalidneg == 0) {
        return(NaN)
    } else {
        suppressWarnings({
            res <- chisq.test(matrix(c(Nmodpos, Nmodneg, Nvalidpos - Nmodpos,
                                       Nvalidneg - Nmodneg), nrow = 2))
        })
        return(sign(res$residuals[1, 1]) * (-log10(res$p.value)))
    }
}

#' Quantify windows by calculating the difference between modification
#'     fractions for the positive and negative strand
#'
#' Calculate sums of per-position \code{Nmod} and \code{Nvalid} counts for
#' positions that overlap windows in \code{gr}, in a strand-specific manner,
#' and calculate \code{FracMod} as the ratio between the two. Then calculate
#' the difference between the \code{FracMod} for the + and - strand.
#'
#' @param se A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object, as generated by \code{readModBam(..., level = "summary")}
#'     (i.e. with the assays \code{"Nmod"} and \code{"Nvalid"}).
#' @param gr A \code{\link[GenomicRanges]{GRanges}} object defining the windows
#'     to quantify.
#' @param pseudocount A numeric scalar with a pseudocount that will be added
#'     to the \code{"Nmod"} and \code{"Nvalid"} before calculating the
#'     modification fraction.
#'
#' @author Charlotte Soneson
#'
#' @returns A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object with one row per window defined by \code{gr} and the window
#'     quantification contained in the assay \code{"FracModDiff"}.
#'
#' @importFrom SummarizedExperiment rowRanges colData assay assayNames
#' @importFrom BiocGenerics strand
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges findOverlaps
#' @importFrom S4Vectors queryHits subjectHits metadata
#' @importFrom cli cli_abort
#'
#' @export
strandDiffFracMod <- function(se, gr, pseudocount = 0) {
    .assertVector(x = se, type = "RangedSummarizedExperiment")
    .assertVector(x = gr, type = "GRanges")
    .assertScalar(x = pseudocount, type = "numeric", rngIncl = c(0, Inf))
    if (!all(c("Nmod", "Nvalid") %in% assayNames(se))) {
        cli_abort("{.arg se} must contain assays Nvalid and Nmod")
    }

    grpos <- grneg <- gr
    strand(grpos) <- "+"
    strand(grneg) <- "-"

    if (nrow(se) > 0) {
        # aggregate counts in windows
        ovpos <- findOverlaps(query = rowRanges(se), subject = grpos,
                              ignore.strand = FALSE)
        ovneg <- findOverlaps(query = rowRanges(se), subject = grneg,
                              ignore.strand = FALSE)
        mNmodpos <- rowsum(x = assay(se, "Nmod")[queryHits(ovpos), ],
                           group = subjectHits(ovpos))
        mNmodneg <- rowsum(x = assay(se, "Nmod")[queryHits(ovneg), ],
                           group = subjectHits(ovneg))
        mNvalidpos <- rowsum(x = assay(se, "Nvalid")[queryHits(ovpos), ],
                             group = subjectHits(ovpos))
        mNvalidneg <- rowsum(x = assay(se, "Nvalid")[queryHits(ovneg), ],
                             group = subjectHits(ovneg))
        rnms <- seq_along(gr)
        mNmodpos <- mNmodpos[match(as.character(rnms), rownames(mNmodpos)), , drop = FALSE]
        mNmodneg <- mNmodneg[match(as.character(rnms), rownames(mNmodneg)), , drop = FALSE]
        mNvalidpos <- mNvalidpos[match(as.character(rnms), rownames(mNvalidpos)), , drop = FALSE]
        mNvalidneg <- mNvalidneg[match(as.character(rnms), rownames(mNvalidneg)), , drop = FALSE]
        if (!is.null(names(gr))) {
            rownames(mNmodpos) <- rownames(mNmodneg) <- rownames(mNvalidpos) <-
                rownames(mNvalidneg) <- names(gr)[as.numeric(rnms)]
        } else {
            rownames(mNmodpos) <- rownames(mNmodneg) <- rownames(mNvalidpos) <-
                rownames(mNvalidneg) <- rnms
        }
        mNmodpos[is.na(mNmodpos)] <- 0
        mNmodneg[is.na(mNmodneg)] <- 0
        mNvalidpos[is.na(mNvalidpos)] <- 0
        mNvalidneg[is.na(mNvalidneg)] <- 0

        stopifnot(exprs = {
            identical(rownames(mNmodpos), rownames(mNvalidpos))
            identical(rownames(mNmodpos), rownames(mNmodneg))
            identical(rownames(mNmodpos), rownames(mNvalidneg))
            all(diff(rnms) > 0)
        })

        # calculate p-values from chi-square test for each row/column
        negLog10P <- matrix(unlist(
            .mapply(.calcDirChiSqP,
                    list(mNmodpos, mNmodneg, mNvalidpos, mNvalidneg),
                    MoreArgs = list())
        ), nrow = nrow(mNmodpos))

        # construct SummarizedExperiment
        seNew <- SummarizedExperiment(
            assays = list(Nmodpos = mNmodpos,
                          Nmodneg = mNmodneg,
                          Nvalidpos = mNvalidpos,
                          Nvalidneg = mNvalidneg,
                          dirNegLog10PValue = negLog10P,
                          FracModDiff = ((mNmodpos + pseudocount) / (mNvalidpos + pseudocount)) -
                              ((mNmodneg + pseudocount) / (mNvalidneg + pseudocount))),
            rowRanges = gr[rnms],
            colData = colData(se),
            metadata = metadata(se))
    } else {
        seNew <- SummarizedExperiment(
            assays = list(Nmodpos = matrix(nrow = 0, ncol = ncol(se)),
                          Nmodneg = matrix(nrow = 0, ncol = ncol(se)),
                          Nvalidpos = matrix(nrow = 0, ncol = ncol(se)),
                          Nvalidneg = matrix(nrow = 0, ncol = ncol(se)),
                          dirNegLog10PValue = matrix(nrow = 0, ncol = ncol(se)),
                          FracModDiff = matrix(nrow = 0, ncol = ncol(se))),
            rowRanges = GRanges(),
            colData = colData(se),
            metadata = metadata(se))
    }

    return(seNew)
}

#' Quantify windows by summing across positions in each of \code{Nmod} and
#'     \code{Nvalid}
#'
#' Calculate sums of per-position \code{Nmod} and \code{Nvalid} counts for
#' positions that overlap windows in \code{gr}, and calculate \code{FracMod}
#' as the ratio between the two.
#'
#' @param se A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object, as generated by \code{readModBam(..., level = "summary")}
#'     (i.e. with the assays \code{"Nmod"} and \code{"Nvalid"}).
#' @param gr A \code{\link[GenomicRanges]{GRanges}} object defining the windows
#'     to quantify.
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object with one row per window defined by \code{gr} and the window
#'     quantifications contained in the assays \code{"Nmod"}, \code{"Nvalid"}
#'     and \code{"FracMod"}. This object is suitable for differential analysis
#'     by \code{getDifferentiallyModifiedWindows}.
#'
#' @examples
#' # TODO
#'
#' @importFrom SummarizedExperiment rowRanges colData assay assayNames
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges findOverlaps
#' @importFrom S4Vectors queryHits subjectHits metadata
#' @importFrom cli cli_abort
#'
#' @export
sumNmodNvalid <- function(se, gr) {
    .assertVector(x = se, type = "RangedSummarizedExperiment")
    .assertVector(x = gr, type = "GRanges")
    if (!all(c("Nmod", "Nvalid") %in% assayNames(se))) {
        cli_abort("{.arg se} must contain assays Nvalid and Nmod")
    }

    if (nrow(se) > 0) {
        # aggregate counts in windows
        ov <- findOverlaps(query = rowRanges(se), subject = gr,
                           ignore.strand = TRUE)
        mNmod <- rowsum(x = assay(se, "Nmod")[queryHits(ov), ],
                        group = subjectHits(ov), reorder = TRUE)
        mNvalid <- rowsum(x = assay(se, "Nvalid")[queryHits(ov), ],
                          group = subjectHits(ov), reorder = TRUE)
        rnms <- as.numeric(rownames(mNmod))
        stopifnot(exprs = {
            identical(rownames(mNmod), rownames(mNvalid))
            all(diff(rnms) > 0)
        })
        if (!is.null(names(gr))) {
            rownames(mNmod) <- rownames(mNvalid) <- names(gr)[rnms]
        } else {
            rownames(mNmod) <- rownames(mNvalid) <- as.character(rnms)
        }

        # construct SummarizedExperiment
        seNew <- SummarizedExperiment(assays = list(Nmod = mNmod,
                                                    Nvalid = mNvalid,
                                                    FracMod = mNmod / mNvalid),
                                      rowRanges = gr[rnms],
                                      colData = colData(se),
                                      metadata = metadata(se))
    } else {
        seNew <- SummarizedExperiment(
            assays = list(Nmod = matrix(nrow = 0, ncol = ncol(se)),
                          Nvalid = matrix(nrow = 0, ncol = ncol(se)),
                          FracMod = matrix(nrow = 0, ncol = ncol(se))),
            rowRanges = GRanges(),
            colData = colData(se),
            metadata = metadata(se))
    }

    return(seNew)
}

#' Quantify windows by calculating a Fourier-transform-based phasing score
#'
#' Calculate a phasing score by decomposing \code{FracMod} in a window into
#' frequency components and extract the \code{numCoef}-th coefficient.
#'
#' @param se A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object, as generated by \code{readModBam(..., level = "summary")}
#'     (i.e. with the assays \code{"Nvalid"} and \code{"FracMod"}).
#' @param gr A \code{\link[GenomicRanges]{GRanges}} object defining the windows
#'     to quantify. Here, the width of the ranges in \code{gr} have to be an
#'     integer multiple of the period of interest (typically
#'     \code{width(gr) = (numCoef - 1) * periodOfInterest}).
#' @param numCoef An integer scalar giving the Fourier coefficient to extract.
#'     The coefficient corresponds to a period of \code{width(gr) / (numCoef - 1)}.
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object with one row per window defined by \code{gr} and the window
#'     phasing scores for periodic signals with a frequency defined by
#'     \code{"numCoef"}.
#'     This object is suitable for transformation by
#'     \code{getRangesWithAssayValues}.
#'
#' @examples
#' library(GenomicRanges)
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' rng <- GRanges("chr1", IRanges(6940000, 6943600))
#' windowStep <- 180
#' windowSize <- 4 * windowStep
#' s <- seq(start(rng), end(rng) - windowSize + 1, by = windowStep)
#' windowgr <- GRanges(seqnames = seqnames(rng),
#'                     ranges = IRanges(start = s, width = windowSize))
#' se <- readModBam(bamfiles = modbamfiles, regions = rng, level = "summary",
#'                  modbase = "a", trim = TRUE,
#'                  BPPARAM = BiocParallel::SerialParam())
#' seFourier <- phasingScoreFourier(se = se, gr = windowgr, numCoef = 5)
#'
#' @importFrom SummarizedExperiment rowRanges colData assay assayNames ncol
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges findOverlaps width start end
#' @importFrom S4Vectors queryHits subjectHits metadata
#' @importFrom BiocGenerics pos
#' @importFrom zoo na.approx
#' @importFrom cli cli_abort
#'
#' @export
phasingScoreFourier <- function(se, gr, numCoef = 5) {
    .assertVector(x = se, type = "RangedSummarizedExperiment")
    .assertVector(x = gr, type = "GRanges")
    .assertPackagesAvailable(pkgs = "e1071")
    if (!all(c("Nvalid", "FracMod") %in% assayNames(se))) {
        cli_abort("{.arg se} must contain assays Nvalid and FracMod")
    }
    if (!all(width(gr) == width(gr)[1])) {
        cli_abort("Not all ranges in {.arg gr} have the same width")
    }
    if (width(gr)[1] %% (numCoef - 1) > 0) {
        cli_abort("{.code width(gr)} is not divisible by {.code numCoef - 1}")
    }
    period <- width(gr)[1] / (numCoef - 1)
    if (!all(diff(start(gr)) == period)) {
        cli_abort("Ranges in {.arg gr} need to be regularly spaced with a shift of {period}")
    }

    if (nrow(se) > 0) {
        # make sure we don't have the same position on both strands
        se <- .pruneAmbiguousStrandPositions(se, assayName = "Nvalid",
                                             verbose = FALSE)

        # loop over samples
        scoresL <- lapply(seq.int(ncol(se)), function(i) {
            # extract FracMod vector
            position <- seq(min(start(gr)), max(end(gr)))
            fracMod <- rep(NA, length(position))
            fracMod[match(pos(rowRanges(se)), position)] <- assay(se, "FracMod")[, i]
            nna <- which(!is.na(fracMod))
            if (length(nna) < length(fracMod)) {
                if (is.na(fracMod[1])) {
                    fracMod[1] <- fracMod[min(nna)]
                }
                if (is.na(fracMod[length(fracMod)])) {
                    fracMod[length(fracMod)] <- fracMod[max(nna)]
                }
            }
            fracMod <- na.approx(fracMod, na.rm = FALSE)

            # Fourier transform
            fit <- e1071::stft(X = fracMod, win = (numCoef - 1) * period,
                               inc = period, coef = 2 * period,
                               wtype = "hanning.window")

            # Extract coefficient of ineterst
            list(scoreAbs = fit$values[, numCoef],
                 scoreRel = fit$values[, numCoef] / rowSums(fit$values))
        })

        # construct SummarizedExperiment
        seNew <- SummarizedExperiment(
            assays = list(
                phasingScoreAbs = do.call(cbind,
                                          lapply(scoresL, "[[", "scoreAbs")),
                phasingScoreRel = do.call(cbind,
                                          lapply(scoresL, "[[", "scoreRel"))),
            rowRanges = gr,
            colData = colData(se),
            metadata = metadata(se))
    } else {
        seNew <- SummarizedExperiment(
            assays = list(
                phasingScoreAbs = matrix(nrow = 0, ncol = ncol(se)),
                phasingScoreRel = matrix(nrow = 0, ncol = ncol(se))),
            rowRanges = GRanges(),
            colData = colData(se),
            metadata = metadata(se))
    }

    return(seNew)
}


#' Generate counts for sequential windows in a single region
#'
#' Read modification data from \code{bamfiles} for a chunk of the genome
#' defined by \code{region} (by calling \code{\link{readModBam}} and aggregate
#' modified and total counts for windows.
#'
#' @param bamfiles Character vector with one or several modBam file names.
#'     Note that no read-filtering will be performed on the data from
#'     these files, so possibly the files should contain only filtered
#'     alignments.
#' @param region A \code{\link[GenomicRanges]{GRanges}} object specifying which
#'     genomic region to extract the reads from. Alternatively, the regions can
#'     be specified as a character scalar (e.g. "chr1:1200-1300") that can be
#'     coerced into a \code{GRanges} object.
#' @param modbase Character vector defining the modified base to extract.
#' @param modProbThreshold A numeric scalar, indicating the modification
#'     probability threshold to use to classify a base as 'modified' or
#'     'unmodified'.
#' @param sampleAnnot A \code{data.frame} (or \code{NULL}) providing annotations
#'     for the samples. It must contain at least one column, named
#'     \code{"sample"}, which must contain all the values of
#'     \code{names(bamfiles)}. The provided annotations will be propagated to
#'     the returned \code{SummarizedExperiment} object.
#' @param seqinfo \code{NULL} or a \code{\link[GenomeInfoDb]{Seqinfo}} object
#'     containing information about the set of genomic sequences (chromosomes).
#'     Alternatively, a named numeric vector with genomic sequence names and
#'     lengths. Useful to set the sorting order of sequence names.
#' @param sequenceContextWidth,sequenceReference Define the sequence
#'     context to be extracted around modified bases. By default (
#'     \code{sequenceContextWidth = 0}), no sequence context will be
#'     extracted, otherwise it will be returned in \code{rowData(x)$sequenceContext}.
#'     See \code{\link{addSeqContext}} for details.
#' @param sequenceContext A character vector with sequence contexts to
#'     retain. To apply this filter, the arguments \code{"sequenceContextWidth"}
#'     and \code{"sequenceReference"} must be set.
#' @param windowMode Character scalar defining how windows in \code{region}
#'     are define. Currently supported are:
#'     \describe{
#'         \item{"fixed"}{: The window is of fixed size (in number of bases),
#'         corresponding to the \code{windowSize} argument value.}
#'         \item{"predefined"}{: The windows are provided by the user, as
#'         a \code{\link[GenomicRanges]{GRanges}} object.}
#'     }
#' @param windowSize Numeric scalar defining the size of windows (see
#'     \code{windowMode} argument).
#' @param windowStep Numeric scalar defining the step (shift) between
#'     start positions of consecutive windows. For non-overlapping
#'     consecutive windows, \code{windowStep} should be equal to
#'     \code{windowSize}.
#' @param windows \code{\link[GenomicRanges]{GRanges}} object with pre-defined
#'     windows (if \code{windowMode = "predefined"}). Only windows where the
#'     midpoint overlaps \code{region} will be considered.
#' @param quantFunction A character scalar giving the name of the window
#'     quantification function. This function should take as a first argument a
#'     \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}} object, as
#'     generated by \code{readModBam}. The second argument should be a
#'     \code{\link[GenomicRanges]{GRanges}} object defining the windows to
#'     quantify. Additional arguments may be passed to \code{quantFunction}
#'     using \code{quantFunctionArgs}. The function must return a
#'     \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}} object
#'     with one row per window defined by the second argument and the window
#'     quantifications contained in the assay(s).
#' @param quantFunctionArgs List with additional arguments for \code{quantFunction}.
#' @param BPPARAM A \code{\link[BiocParallel]{BiocParallelParam}} object that
#'     controls the number of parallel CPU threads to use for some of the steps
#'     in \code{readModBam()}. The default value is
#'     (\code{\link[BiocParallel]{MulticoreParam}(4L, RNGseed = 42L)}).
#'     If randomly sampling reads (\code{nAlnsToSample > 0}), make sure to set
#'     the \code{RNGseed} argument when constructing the \code{BPPARAM} object
#'     for reproducible results (see also
#'     \code{vignette("Random_Numbers", package = "BiocParallel")}).
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @author Panagiotis Papasaikas, Sebastien Smallwood, Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[SummarizedExperiment]{SummarizedExperiment}} object
#'     with columns corresponding to samples (the elements of \code{bamfiles})
#'     and rows corresponding to windows in \code{region}. The object contains
#'     the assays \code{"Nmod"} and \code{"Nvalid"} containing the number of
#'     modified and total (valid) bases in each window and sample, respectively.
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' gnmfasta <- system.file("extdata", "reference.fa.gz", package = "footprintR")
#' quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                         region = "chr1:6940000-6955000",
#'                         modbase = "a",
#'                         sequenceContextWidth = 1,
#'                         sequenceReference = gnmfasta,
#'                         sequenceContext = "A",
#'                         BPPARAM = BiocParallel::SerialParam())
#' quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                         region = "chr1:6940000-6955000",
#'                         modbase = "a",
#'                         BPPARAM = BiocParallel::SerialParam())
#'
#' @importFrom SummarizedExperiment colData
#' @importFrom GenomicRanges GRanges GPos
#' @importFrom IRanges IRanges start end findOverlaps overlapsAny
#' @importFrom S4Vectors queryHits subjectHits metadata
#' @importFrom cli cli_abort
#'
#' @export
quantifyWindowsInRegion <- function(bamfiles,
                                    region,
                                    modbase,
                                    modProbThreshold = 0.5,
                                    sampleAnnot = NULL,
                                    seqinfo = NULL,
                                    sequenceContextWidth = 0,
                                    sequenceReference = NULL,
                                    sequenceContext = NULL,
                                    windowMode = "fixed",
                                    windowSize = 24,
                                    windowStep = round(windowSize / 2),
                                    windows = NULL,
                                    quantFunction = "sumNmodNvalid",
                                    quantFunctionArgs = list(),
                                    BPPARAM = MulticoreParam(4L, RNGseed = 42L),
                                    verbose = FALSE) {
    # check parameters
    if (is.character(region)) {
        region <- .regionStringToGRanges(region, seqinfo = seqinfo)
    }
    if (windowMode == "predefined") {
        .assertVector(x = region, type = "GRanges")
    } else {
        .assertScalar(x = region, type = "GRanges")
    }
    .assertScalar(x = modbase, type = "character")
    .assertScalar(x = windowMode, type = "character",
                  validValues = c("fixed", "predefined"))
    if (windowMode == "fixed") {
        .assertScalar(x = windowSize, type = "numeric", rngIncl = c(1L, Inf))
        .assertScalar(x = windowStep, type = "numeric", rngIncl = c(1L, Inf))
    } else if (windowMode == "predefined") {
        .assertVector(x = windows, type = "GRanges")
    }
    .assertScalar(x = quantFunction, type = "character")
    if (!exists(quantFunction)) {
        cli_abort("{.arg quantFunction} must be the name of an existing function")
    }

    # read summary-level data
    se <- readModBam(bamfiles = bamfiles, regions = region, modbase = modbase,
                     level = "summary", sampleAnnot = sampleAnnot,
                     seqinfo = seqinfo,
                     sequenceContextWidth = sequenceContextWidth,
                     sequenceReference = sequenceReference,
                     modProbThreshold = modProbThreshold,
                     trim = TRUE, BPPARAM = BPPARAM,
                     verbose = verbose)

    # filter positions
    if (!is.null(sequenceContext)) {
        se <- filterPositions(se = se, filters = "sequenceContext",
                              sequenceContext = sequenceContext,
                              assayNameNA = NULL)
    }

    # define windows for aggregation
    if (nrow(se) > 0) {
        if (identical(windowMode, "fixed")) {
            s <- seq(start(region), end(region) - windowSize + 1,
                     by = windowStep)
            windowgr <- GRanges(seqnames = seqnames(region),
                                ranges = IRanges(start = s,
                                                 width = windowSize))
        } else if (identical(windowMode, "predefined")) {
            windowgr <- windows[overlapsAny(
                resize(windows, width = 1, fix = "center"),
                region, ignore.strand = TRUE)]
        }
    } else {
        windowgr <- GRanges()
    }

    # quantify windows using quantFunction
    seNew <- do.call(quantFunction, c(list(quote(se), quote(windowgr)),
                                      quantFunctionArgs))

    return(seNew)
}


#' Analyze counts for sequential windows in a single region
#'
#' Given a \code{SummarizedExperiment} with modified and total
#' base counts in assays \code{"Nmod"} and \code{"Nvalid"},
#' perform a pairwise statistical test for differential modification.
#'
#' @param se \code{SummarizedExperiment}, for example returned by
#'     \code{quantifyWindowsInRegion}. It is expected to at least
#'     contain assays for modified and total counts (given by
#'     \code{assayNameMod} and \code{assayNameValid}) and
#'     a \code{colData} column that defines the groups (given
#'     by \code{groupCol}).
#' @param assayNameMod,assayNameValid Character scalars that give
#'     the assay names in \code{se} containing the modified and
#'     total counts, respectively.
#' @param groupCol Character scalar giving the column in \code{colData(se)}
#'     that defines the groups of samples to be compared.
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @author Panagiotis Papasaikas, Sebastien Smallwood, Charlotte Soneson, Michael Stadler
#'
#' @returns The \code{\link[GenomicRanges]{GRanges}} object constructed from
#'     the \code{\link[edgeR]{topTags}} output obtained for the statistical
#'     analysis, with an additional column named "dirNegLog10PValue", calculated
#'     as the sign of the logFC multiplied with the -log10(PValue).
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_1_10reads.bam",
#'                              "6mA_2_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' se <- quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                               region = "chr1:6940000-6955000", modbase = "a",
#'                               BPPARAM = BiocParallel::SerialParam())
#' se$group <- c("group1", "group1", "group2", "group2")
#' gr <- getDifferentiallyModifiedWindows(se, groupCol = "group")
#' class(gr)
#' head(gr)
#'
#' @importFrom SummarizedExperiment assayNames colData assay ncol
#' @importFrom GenomicRanges GRanges
#' @importFrom S4Vectors mcols<- DataFrame
#' @importFrom stats model.matrix
#' @importFrom methods as
#' @importFrom cli cli_abort
#'
#' @export
getDifferentiallyModifiedWindows <- function(se,
                                             assayNameMod = "Nmod",
                                             assayNameValid = "Nvalid",
                                             groupCol = "group",
                                             verbose = FALSE) {
    # check arguments
    .assertVector(x = se, type = "SummarizedExperiment")
    .assertScalar(x = assayNameMod, type = "character",
                  validValues = assayNames(se))
    .assertScalar(x = assayNameValid, type = "character",
                  validValues = assayNames(se))
    .assertScalar(x = groupCol, type = "character",
                  validValues = colnames(colData(se)))
    if (length(unique(colData(se)[[groupCol]])) != 2) {
        cli_abort(paste0(
            "The group column in {.code colData(se)} ({groupCol}) ",
            "needs to have exactly two unique values."))
    }
    .assertScalar(x = verbose, type = "logical")
    .assertPackagesAvailable(pkgs = "edgeR")

    if (nrow(se) > 0) {
        # calculate library size and unmodified counts
        .message("calculating library sizes and normalization factors")
        libsizes <- colSums(assay(se, assayNameValid))
        nfacts <- edgeR::normLibSizes(assay(se, assayNameValid))
        cnt <- cbind(assay(se, assayNameMod),
                     assay(se, assayNameValid) - assay(se, assayNameMod))
        cd2 <- cbind(rbind(colData(se)[, c("sample", groupCol)],
                           colData(se)[, c("sample", groupCol)]),
                     data.frame(type = rep(c("mod", "unmod"), each = ncol(se))))
        cd2$group <- factor(cd2$group)

        # create design matrix
        .message("creating design matrix")
        dsgn <- model.matrix(~ 0 + sample, data = cd2)
        for (grp in levels(cd2$group)) {
            dsgn <- cbind(dsgn, cd2$group == grp & cd2$type == "mod")
        }
        colnames(dsgn)[ncol(dsgn) - c(1, 0)] <- levels(cd2$group)
        rownames(cnt) <- NULL
        colnames(cnt) <- rownames(dsgn) <- paste0(rep(colnames(se), 2),
                                                  rep(c(".mod", ".unmod"),
                                                      each = ncol(se)))

        # test for differential modification
        .message("testing for differential modifications")
        dgeL <- edgeR::DGEList(counts = cnt, lib.size = rep(libsizes, 2),
                               norm.factors = rep(nfacts, 2),
                               genes = as.data.frame(unname(rowRanges(se))))
        dgeL <- edgeR::estimateDisp(y = dgeL, design = dsgn)
        fit <- edgeR::glmFit(y = dgeL, design = dsgn)
        tst <- edgeR::glmLRT(
            glmfit = fit,
            contrast = (colnames(dsgn) == levels(cd2$group)[2]) -
                (colnames(dsgn) == levels(cd2$group)[1]))

        # coerce topTags to GRanges
        tt <- edgeR::topTags(object = tst, n = Inf, sort.by = "none")
        tt$table$dirNegLog10PValue <- sign(tt$table$logFC) * -log10(tt$table$PValue)
        gr <- as(tt$table, "GRanges")
    } else {
        gr <- GRanges()
        mcols(gr) <- DataFrame(logFC = numeric(0),
                               logCPM = numeric(0),
                               LR = numeric(0),
                               PValue = numeric(0),
                               FDR = numeric(0),
                               dirNegLog10PValue = numeric(0))
    }
    return(gr)
}

#' Create a \code{GRanges} from a \code{SummarizedExperiment}.
#'
#' Create a \code{GRanges} object from \code{rowRanges} and \code{assay} of
#' a \code{SummarizedExperiment} object.
#'
#' @param se \code{RangedSummarizedExperiment} object, for example returned by
#'     \code{quantifyWindowsInRegion}.
#' @param assayName Character scalar defining the assay to be extracted from
#'     \code{se} and set as \code{mcols(...)} of the return value. Thus, each
#'     column of the assay will become a column in \code{mcols(...)}.
#'     If missing, the first assay from \code{se} will be used.
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[GenomicRanges]{GRanges}} object, with the selected
#'     assay in its metadata columns.
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_1_10reads.bam",
#'                              "6mA_2_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' se <- quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                               region = "chr1:6940000-6955000", modbase = "a",
#'                               BPPARAM = BiocParallel::SerialParam())
#' gr <- getRangesWithAssayValues(se, assayName = "Nmod")
#' gr
#'
#' @importFrom SummarizedExperiment rowRanges assay assayNames colnames
#' @importFrom S4Vectors mcols<-
#'
#' @export
getRangesWithAssayValues <- function(se, assayName) {
    .assertVector(x = se, type = "RangedSummarizedExperiment")
    if (missing(assayName)) {
        assayName <- assayNames(se)[1]
    }
    .assertVector(x = assayName, type = "character",
                  validValues = assayNames(se))

    gr <- rowRanges(se)
    for (an in assayName) {
        tmp <- assay(se, an)
        colnames(tmp) <- paste0(an, ".", colnames(se))
        mcols(gr) <- cbind(mcols(gr), tmp)
    }

    return(gr)
}

#' Process scores of sequential genomic windows.
#'
#' Given scores or statistical estimates for sequential windows,
#' process them according to the \code{scoreAction} argument.
#' Typical actions are to smooth the scores and possibly identify
#' regions of interest by fusing consistent neighboring windows
#' along the genome.
#'
#' @param x \code{GRanges} object with window-based scores or estimates.
#'     Ranges correspond to windows, and columns in \code{mcols(x)} to scores.
#' @param scoreCol Character scalar giving the column name in \code{mcols(x)}
#'     to use for the analysis. For \code{scanForHighScoringRegions}, it can
#'     be a vector, in which case \code{processWindowScores} will be run for
#'     each of them and the results will be returned as a list.
#' @param scoreAction A character scalar indicating how to process the
#'     scores. Currently supported values are:
#'     \describe{
#'         \item{pass}{: Do not modify window scores (pass-through). Note that
#'             if \code{mcols(x)} has multiple columns, they will all be
#'             passed through (i.e., \code{scoreCol} is ignored). To return
#'             only \code{scoreCol}, use \code{select}.}
#'         \item{select}{: Pass through only \code{scoreCol}.}
#'         \item{smooth}{: Smooth window scores (\code{minperiod} argument).}
#'         \item{smoothFuse (default)}{: Smooth window scores, identify high
#'             scoring elements (\code{thresh} argument) and fuse nearby
#'             high-scoring elements (\code{maxGap} argument).
#'         }
#'     }
#' @param minperiod Numeric scalar that defines the low-pass
#'     filter parameter used to smooth the scores for segmentation.
#'     \code{minperiod} gives the minimal period (in number of windows) for the
#'     critical frequency in the score signal that should be retained. The
#'     default value is suitable to retain signals that occur in three
#'     neighboring windows. The filtering is performed using
#'     \code{\link[signal]{filtfilt}} and thus requires the \code{signal}
#'     package to be installed.
#' @param thresh A numeric scalar giving the minimal absolute window score
#'     (after smoothing, see \code{minperiod} argument) defining a region of
#'     interest. Higher values make the region detection more stringent.
#' @param maxGap Numeric scalar giving the maximal gap between neighboring
#'     windows, in base pairs, from the end of the first to the start of the
#'     next, to be fused into a single region of interest.
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @author Sebastien Smallwood, Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[GenomicRanges]{GRanges}} object. For \code{scoreAction}
#'     equal to \code{"pass"} or \code{"smooth"}, the returned object has the same
#'     dimensions as the input object \code{x}. For \code{scoreAction="smoothFuse"},
#'     the returned object will only contain thresholded, fused regions.
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_1_10reads.bam",
#'                              "6mA_2_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' se <- quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                               region = "chr1:6940000-6955000", modbase = "a",
#'                               BPPARAM = BiocParallel::SerialParam())
#' se$group <- c("group1", "group1", "group2", "group2")
#' gr <- getDifferentiallyModifiedWindows(se, groupCol = "group")
#' gr
#'
#' grFused <- processWindowScores(x = gr, scoreCol = "logFC", thresh = 5.0)
#' grFused
#'
#' @importFrom GenomicRanges GRanges
#' @importFrom BiocGenerics sort
#' @importFrom S4Vectors mcols mcols<- subjectHits queryHits DataFrame
#' @importFrom dplyr mutate filter group_by ungroup group_split
#' @importFrom IRanges reduce findOverlaps
#' @importFrom cli cli_abort
#' @importFrom rlang .data
#'
#' @export
processWindowScores <- function(
        x,
        scoreCol = "dirNegLog10PValue",
        scoreAction = c("smoothFuse", "smooth", "pass", "select"),
        minperiod = 3,
        thresh = 3,
        maxGap = 50,
        verbose = FALSE) {
    # check argument values
    .assertVector(x = x, type = "GRanges")
    .assertScalar(x = scoreCol, type = "character",
                  validValues = colnames(mcols(x)))
    scoreAction <- match.arg(scoreAction)
    .assertScalar(x = thresh, type = "numeric", rngExcl = c(0, Inf))
    .assertScalar(x = minperiod, type = "numeric", rngIncl = c(0, Inf))
    .assertScalar(x = maxGap, type = "numeric", rngIncl = c(0, Inf))
    .assertScalar(x = verbose, type = "logical")
    if (scoreAction %in% c("smoothFuse", "smooth")) {
        .assertPackagesAvailable(pkgs = "signal")
    }

    # do we just pass-through the input?
    if (identical(scoreAction, "pass")) {
        .message("passing-through window scores")
        gr <- x
    } else if (identical(scoreAction, "select")) {
        .message("passing-through selected window scores")
        gr <- x
        mcols(gr) <- mcols(gr)[, scoreCol, drop = FALSE]
    } else {
        # smooth scores
        .message("smoothing windows")
        xdf <- data.frame(unname(x), check.names = FALSE) |>
            mutate(chunkId = cumsum(c(1, (start[-1] - end[-length(x)] > maxGap |
                                              seqnames[-1] != seqnames[-length(x)])))) |>
            group_by(.data$chunkId) |>
            mutate(sscore = .filterScores(.data[[scoreCol]],
                                          minperiod = minperiod,
                                          maxperiod = Inf,
                                          type = "low")) |>
            ungroup()

        if (identical(scoreAction, "smooth")) {
            gr <- x
            mcols(gr)[[scoreCol]] <- xdf$sscore

        } else if (identical(scoreAction, "smoothFuse")) {
            # threshold
            .message("thresholding smoothed scores")
            xdfSel <- xdf |>
                dplyr::filter(abs(.data$sscore) >= thresh) |>
                mutate(direction = factor(ifelse(sign(.data$sscore) == -1,
                                                 "negative", "positive"),
                                          levels = c("negative", "positive")))

            # summarise
            .message("summarise {nrow(xdfSel)} window{?s} into regions of interest")
            grL <- xdfSel |>
                group_by(.data$direction) |>
                group_split() |>
                lapply(function(x) {
                    gr1 <- as(x, "GRanges") |>
                        reduce(min.gapwidth = maxGap)
                    ov1 <- findOverlaps(query = as(x, "GRanges"),
                                        subject = gr1, type = "within")
                    mcols(gr1)[[paste0(scoreCol, "Thresh")]] <- as.vector(
                        tapply(X = x$sscore[queryHits(ov1)],
                               INDEX = subjectHits(ov1),
                               FUN = mean))
                    mcols(gr1)[["numWindowsThresh"]] <- tabulate(subjectHits(ov1))
                    gr1$direction <- x$direction[1]
                    gr1
                })
            if (sum(lengths(grL)) > 0) {
                gr <- sort(sort(do.call(c, grL)), ignore.strand = TRUE)
                ov <- findOverlaps(query = x, subject = gr, type = "within")
                mcols(gr)[[scoreCol]] <- as.vector(
                    tapply(X = xdf$sscore[queryHits(ov)],
                           INDEX = subjectHits(ov),
                           FUN = mean))
                mcols(gr)[["numWindows"]] <- tabulate(subjectHits(ov))
            } else {
                gr <- GRanges()
                mcols(gr) <- DataFrame(thresh = numeric(0),
                                       numWindowsThresh = integer(0),
                                       direction = factor(character(0),
                                                          levels = c("negative",
                                                                     "positive")),
                                       score = numeric(0),
                                       numWindows = numeric(0))
                colnames(mcols(gr))[c(1,4)] <- paste0(scoreCol, c("Thresh", ""))
            }
        }
    }

    return(gr)
}

#' Scan one or more chromosomes for high-scoring regions
#'
#' Given one or several modBam files and a vector with chromosome lengths,
#' quantify the modification data in windows using \code{quantFunction},
#' calculate a score for each window using \code{scoreFunction} and fuse
#' neighboring high-scoring windows. For example, the quantification could
#' sum up observed counts in each window (implemented in \code{sumNmodNvalid}),
#' and the score could be a directional P value measuring differential
#' modification between two groups of modBam files (implemented in
#' \code{getDifferentiallyModifiedWindows}), and the identified windows would
#' then be differentially modified regions (DMRs). Please note that
#' \code{quantFunction} needs to be compatible with \code{scoreFunction}, as
#' the latter consumes the output of the former.
#'
#' @inheritParams quantifyWindowsInRegion
#' @inheritParams processWindowScores
#'
#' @param chromosomeLengths A named character vector with lengths of
#'     chromosomes to be analyzed, for example the return value of
#'     \code{seqlengths(BSgenomeObject)}.
#' @param scoreFunction A character scalar giving the name of the scoring
#'     function. This function should take as a first argument a
#'     \code{\link[SummarizedExperiment]{SummarizedExperiment}} object, as
#'     generated by \code{quantifyWindowsInRegion}. Additional arguments may
#'     be passed to \code{scoreFunction} using \code{scoreFunctionArgs}. The
#'     function must return a \code{\link[GenomicRanges]{GRanges}} object
#'     (typically corresponding to the \code{rowRanges} of the input) with the
#'     score added to the \code{mcols()}.
#' @param scoreFunctionArgs List with additional arguments for \code{scoreFunction}.
#' @param tileSize A numeric scalar giving the approximate size of a
#'     genomic region for which the data is loaded at once. Chromosomes that
#'     are larger than \code{tileSize} will be automatically split into
#'     multiple tiles. Reduce this size if you would like to reduce the memory
#'     usage of the function.
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[GenomicRanges]{GRanges}} object with identified
#'     regions of interest, or a named list of such objects if
#'     \code{scoreCol} is a vector of length >1.
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_1_10reads.bam",
#'                              "6mA_2_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' gr <- scanForHighScoringRegions(
#'     bamfiles = modbamfiles,
#'     sampleAnnot = data.frame(sample = c("s1","s2","s3","s4"),
#'                              group = c("A","A","B","B")),
#'     chromosomeLengths = c(chr1 = 6955000),
#'     modbase = "a", BPPARAM = BiocParallel::SerialParam())
#' gr
#'
#' @importFrom BiocParallel MulticoreParam
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges IRanges
#' @importFrom cli cli_abort
#' @importFrom stats setNames
#'
#' @export
scanForHighScoringRegions <- function(
        bamfiles,
        sampleAnnot,
        chromosomeLengths,
        quantFunction = "sumNmodNvalid",
        quantFunctionArgs = list(),
        scoreFunction = "getDifferentiallyModifiedWindows",
        scoreFunctionArgs = list(),
        modbase,
        modProbThreshold = 0.5,
        tileSize = 1e6,
        seqinfo = NULL,
        sequenceContextWidth = 0,
        sequenceReference = NULL,
        sequenceContext = NULL,
        windowMode = "fixed",
        windowSize = 24,
        windowStep = round(windowSize/2),
        scoreCol = "dirNegLog10PValue",
        scoreAction = "smoothFuse",
        minperiod = 3,
        thresh = 3,
        maxGap = 50,
        BPPARAM = MulticoreParam(4L, RNGseed = 42L),
        verbose = FALSE) {
    # check parameters
    .assertVector(x = chromosomeLengths, type = "numeric")
    if (is.null(names(chromosomeLengths)) ||
        any(duplicated(names(chromosomeLengths))) ||
        any(names(chromosomeLengths) == "")) {
        cli_abort("{.arg chromosomeLengths} must be a named vector")
    }
    .assertScalar(x = scoreFunction, type = "character")
    if (!exists(scoreFunction)) {
        cli_abort("{.arg scoreFunction} must be the name of an existing function")
    }
    .assertScalar(x = tileSize, type = "numeric", rngExcl = c(0, Inf))

    # loop over chromosomes
    grL <- lapply(names(chromosomeLengths), function(chr) {
        regs <- .tileChromosome(tileSize = tileSize,
                                windowSize = windowSize,
                                windowStep = windowStep,
                                chromName = chr,
                                chromLength = chromosomeLengths[chr])

        # quantify windows for each tile and merge
        tileL <- lapply(seq_along(regs), function(i) {
            quantifyWindowsInRegion(bamfiles = bamfiles,
                                    region = regs[i],
                                    modbase = modbase,
                                    modProbThreshold = modProbThreshold,
                                    sampleAnnot = sampleAnnot,
                                    seqinfo = seqinfo,
                                    sequenceContextWidth = sequenceContextWidth,
                                    sequenceReference = sequenceReference,
                                    sequenceContext = sequenceContext,
                                    windowMode = windowMode,
                                    windowSize = windowSize,
                                    windowStep = windowStep,
                                    quantFunction = quantFunction,
                                    quantFunctionArgs = quantFunctionArgs,
                                    BPPARAM = BPPARAM,
                                    verbose = verbose)
        })
        se <- do.call(rbind, tileL[unlist(lapply(tileL, function(x) nrow(x) > 0))])

        # calculate window scores
        grScores <- do.call(scoreFunction, c(list(quote(se)), scoreFunctionArgs))

        # fuse windows
        grScoresFused <- lapply(setNames(scoreCol, scoreCol), function(sc) {
            processWindowScores(x = grScores,
                                scoreCol = sc,
                                scoreAction = scoreAction,
                                minperiod = minperiod,
                                thresh = thresh,
                                maxGap = maxGap,
                                verbose = verbose)
        })

        # return fused windows
        return(grScoresFused)
    })
    gr <- lapply(setNames(scoreCol, scoreCol), function(sc) {
        do.call(c, lapply(grL, "[[", sc))
    })
    if (length(scoreCol) == 1) {
        gr <- gr[[1]]
    }

    return(gr)
}
