#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges IRanges
#' @keywords internal
#' @noRd
.tileChromosome <- function(tileSize,
                            windowSize,
                            windowStep,
                            chromName,
                            chromLength) {
    # tile a chromosome
    nWindowsPerTile <- floor(tileSize / windowStep)
    tileSize <- ((nWindowsPerTile - 1) * windowStep) + windowSize
    nTiles <- ceiling((chromLength - (windowSize - windowStep)) / (tileSize - (windowSize - windowStep)))
    s <- 1 + (seq.int(nTiles) - 1) * (tileSize - windowSize + windowStep)
    regs <- GRanges(chromName, IRanges(start = s, width = tileSize))
    regs
}

#' Calculate directed p-value from chi-square test
#'
#' @keywords internal
#' @noRd
#' @importFrom stats chisq.test
.calcDirChiSqP <- function(Nmodpos, Nmodneg, Nvalidpos, Nvalidneg) {
    if (Nvalidpos + Nvalidneg == 0) {
        return(NaN)
    } else {
        suppressWarnings({
            res <- chisq.test(matrix(c(Nmodpos, Nmodneg, Nvalidpos - Nmodpos,
                                       Nvalidneg - Nmodneg), nrow = 2))
        })
        return(sign(res$residuals[1, 1]) * (-log10(res$p.value)))
    }
}

#' Quantify windows by calculating the difference between modification
#'     fractions for the positive and negative strand
#'
#' Calculate sums of per-position \code{Nmod} and \code{Nvalid} counts for
#' positions that overlap windows in \code{gr}, in a strand-specific manner,
#' and calculate \code{FracMod} as the ratio between the two. Then calculate
#' the difference between the \code{FracMod} for the + and - strand.
#'
#' @param se A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object, as generated by \code{readModBam(..., level = "summary")}
#'     (i.e. with the assays \code{"Nmod"} and \code{"Nvalid"}).
#' @param gr A \code{\link[GenomicRanges]{GRanges}} object defining the windows
#'     to quantify.
#' @param pseudocount A numeric scalar with a pseudocount that will be added
#'     to the \code{"Nmod"} and \code{"Nvalid"} before calculating the
#'     modification fraction.
#'
#' @author Charlotte Soneson
#'
#' @returns A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object with one row per window defined by \code{gr} and the window
#'     quantification contained in the assay \code{"FracModDiff"}.
#'
#' @examples
#' library(GenomicRanges)
#' library(SummarizedExperiment)
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' se <- readModBam(bamfiles = modbamfiles, regions = "chr1:6940000-6940500",
#'                  level = "summary", modbase = "a", trim = TRUE,
#'                  BPPARAM = BiocParallel::SerialParam())
#' s <- seq(6940000, 6940400, by = 100)
#' windowgr <- GRanges(seqnames = "chr1",
#'                     ranges = IRanges(start = s, width = 100, names = letters[1:5]))
#' seStrandDiff <- strandDiffFracMod(se = se, gr = windowgr)
#' seStrandDiff
#' assayNames(seStrandDiff)
#' assay(seStrandDiff, "Nvalidpos")
#' assay(seStrandDiff, "Nvalidneg")
#'
#' @importFrom SummarizedExperiment rowRanges colData assay assayNames
#' @importFrom BiocGenerics strand
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges findOverlaps
#' @importFrom S4Vectors queryHits subjectHits metadata
#' @importFrom cli cli_abort
#'
#' @export
strandDiffFracMod <- function(se, gr, pseudocount = 0) {
    .assertVector(x = se, type = "RangedSummarizedExperiment")
    .assertVector(x = gr, type = "GRanges")
    .assertScalar(x = pseudocount, type = "numeric", rngIncl = c(0, Inf))
    if (!all(c("Nmod", "Nvalid") %in% assayNames(se))) {
        cli_abort("{.arg se} must contain assays Nvalid and Nmod")
    }

    grpos <- grneg <- gr
    strand(grpos) <- "+"
    strand(grneg) <- "-"

    if (nrow(se) > 0) {
        # aggregate counts in windows
        ovpos <- findOverlaps(query = rowRanges(se), subject = grpos,
                              ignore.strand = FALSE)
        ovneg <- findOverlaps(query = rowRanges(se), subject = grneg,
                              ignore.strand = FALSE)
        mNmodpos <- rowsum(x = assay(se, "Nmod")[queryHits(ovpos), , drop = FALSE],
                           group = subjectHits(ovpos))
        mNmodneg <- rowsum(x = assay(se, "Nmod")[queryHits(ovneg), , drop = FALSE],
                           group = subjectHits(ovneg))
        mNvalidpos <- rowsum(x = assay(se, "Nvalid")[queryHits(ovpos), , drop = FALSE],
                             group = subjectHits(ovpos))
        mNvalidneg <- rowsum(x = assay(se, "Nvalid")[queryHits(ovneg), , drop = FALSE],
                             group = subjectHits(ovneg))
        rnms <- seq_along(gr)
        mNmodpos <- mNmodpos[match(as.character(rnms), rownames(mNmodpos)), , drop = FALSE]
        mNmodneg <- mNmodneg[match(as.character(rnms), rownames(mNmodneg)), , drop = FALSE]
        mNvalidpos <- mNvalidpos[match(as.character(rnms), rownames(mNvalidpos)), , drop = FALSE]
        mNvalidneg <- mNvalidneg[match(as.character(rnms), rownames(mNvalidneg)), , drop = FALSE]
        if (!is.null(names(gr))) {
            rownames(mNmodpos) <- rownames(mNmodneg) <- rownames(mNvalidpos) <-
                rownames(mNvalidneg) <- names(gr)[as.numeric(rnms)]
        } else {
            rownames(mNmodpos) <- rownames(mNmodneg) <- rownames(mNvalidpos) <-
                rownames(mNvalidneg) <- rnms
        }
        mNmodpos[is.na(mNmodpos)] <- 0
        mNmodneg[is.na(mNmodneg)] <- 0
        mNvalidpos[is.na(mNvalidpos)] <- 0
        mNvalidneg[is.na(mNvalidneg)] <- 0

        stopifnot(exprs = {
            identical(rownames(mNmodpos), rownames(mNvalidpos))
            identical(rownames(mNmodpos), rownames(mNmodneg))
            identical(rownames(mNmodpos), rownames(mNvalidneg))
            all(diff(rnms) > 0)
        })

        # calculate p-values from chi-square test for each row/column
        negLog10P <- matrix(unlist(
            .mapply(.calcDirChiSqP,
                    list(mNmodpos, mNmodneg, mNvalidpos, mNvalidneg),
                    MoreArgs = list())
        ), nrow = nrow(mNmodpos))

        # construct SummarizedExperiment
        seNew <- SummarizedExperiment(
            assays = list(Nmodpos = mNmodpos,
                          Nmodneg = mNmodneg,
                          Nvalidpos = mNvalidpos,
                          Nvalidneg = mNvalidneg,
                          dirNegLog10PValue = negLog10P,
                          FracModDiff = ((mNmodpos + pseudocount) / (mNvalidpos + pseudocount)) -
                              ((mNmodneg + pseudocount) / (mNvalidneg + pseudocount))),
            rowRanges = gr[rnms],
            colData = colData(se),
            metadata = metadata(se))
    } else {
        seNew <- SummarizedExperiment(
            assays = list(Nmodpos = matrix(nrow = 0, ncol = ncol(se)),
                          Nmodneg = matrix(nrow = 0, ncol = ncol(se)),
                          Nvalidpos = matrix(nrow = 0, ncol = ncol(se)),
                          Nvalidneg = matrix(nrow = 0, ncol = ncol(se)),
                          dirNegLog10PValue = matrix(nrow = 0, ncol = ncol(se)),
                          FracModDiff = matrix(nrow = 0, ncol = ncol(se))),
            rowRanges = GRanges(),
            colData = colData(se),
            metadata = metadata(se))
    }

    return(seNew)
}

#' Quantify windows by summing across positions in each of \code{Nmod} and
#'     \code{Nvalid}
#'
#' Calculate sums of per-position \code{Nmod} and \code{Nvalid} counts for
#' positions that overlap windows in \code{gr}, and calculate \code{FracMod}
#' as the ratio between the two.
#'
#' @param se A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object, as generated by \code{readModBam(..., level = "summary")}
#'     (i.e. with the assays \code{"Nmod"} and \code{"Nvalid"}).
#' @param gr A \code{\link[GenomicRanges]{GRanges}} object defining the windows
#'     to quantify.
#' @param includeEmpty Logical scalar. If \code{TRUE}, include also windows
#'     without overlapping modified bases in the output (with zero counts
#'     in both the Nmod and Nvalid assays).
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object with one row per window defined by \code{gr} and the window
#'     quantifications contained in the assays \code{"Nmod"}, \code{"Nvalid"}
#'     and \code{"FracMod"}. This object is suitable for differential analysis
#'     by \code{getDifferentiallyModifiedWindows}.
#'
#' @examples
#' library(GenomicRanges)
#' library(SummarizedExperiment)
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' se <- readModBam(bamfiles = modbamfiles, regions = "chr1:6940000-6940500",
#'                  level = "summary", modbase = "a", trim = TRUE,
#'                  BPPARAM = BiocParallel::SerialParam())
#' s <- seq(6940000, 6940400, by = 100)
#' windowgr <- GRanges(seqnames = "chr1",
#'                     ranges = IRanges(start = s, width = 100, names = letters[1:5]))
#' seSum <- sumNmodNvalid(se = se, gr = windowgr)
#' seSum
#' assay(seSum, "Nvalid")
#'
#' @importFrom SummarizedExperiment rowRanges colData assay assayNames
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges findOverlaps
#' @importFrom S4Vectors queryHits subjectHits metadata
#' @importFrom cli cli_abort
#'
#' @export
sumNmodNvalid <- function(se, gr, includeEmpty = FALSE) {
    .assertVector(x = se, type = "RangedSummarizedExperiment")
    .assertVector(x = gr, type = "GRanges")
    .assertScalar(x = includeEmpty, type = "logical")
    if (!all(c("Nmod", "Nvalid") %in% assayNames(se))) {
        cli_abort("{.arg se} must contain assays Nvalid and Nmod")
    }

    if (nrow(se) > 0) {
        # aggregate counts in windows
        ov <- findOverlaps(query = rowRanges(se), subject = gr,
                           ignore.strand = TRUE)
        mNmodtmp <- rowsum(
            x = assay(se, "Nmod")[queryHits(ov), , drop = FALSE],
            group = subjectHits(ov), reorder = TRUE)
        mNvalidtmp <- rowsum(
            x = assay(se, "Nvalid")[queryHits(ov), , drop = FALSE],
            group = subjectHits(ov), reorder = TRUE)
        if (includeEmpty) {
            # some regions may not have any overlapping modified bases -
            # return 0 for those
            mNmod <- matrix(0, nrow = length(gr), ncol = ncol(mNmodtmp),
                            dimnames = list(seq_along(gr),
                                            colnames(mNmodtmp)))
            mNmod[rownames(mNmodtmp), ] <- mNmodtmp
            mNvalid <- matrix(0, nrow = length(gr), ncol = ncol(mNvalidtmp),
                              dimnames = list(seq_along(gr),
                                              colnames(mNvalidtmp)))
            mNvalid[rownames(mNvalidtmp), ] <- mNvalidtmp
        } else {
            # don't return empty rows
            mNmod <- mNmodtmp
            mNvalid <- mNvalidtmp
        }

        rnms <- as.numeric(rownames(mNmod))
        stopifnot(exprs = {
            identical(rownames(mNmod), rownames(mNvalid))
            all(diff(rnms) > 0)
        })
        if (!is.null(names(gr))) {
            rownames(mNmod) <- rownames(mNvalid) <- names(gr)[rnms]
        } else {
            rownames(mNmod) <- rownames(mNvalid) <- as.character(rnms)
        }

        # construct SummarizedExperiment
        seNew <- SummarizedExperiment(assays = list(Nmod = mNmod,
                                                    Nvalid = mNvalid,
                                                    FracMod = mNmod / mNvalid),
                                      rowRanges = gr[rnms],
                                      colData = colData(se),
                                      metadata = metadata(se))
    } else {
        seNew <- SummarizedExperiment(
            assays = list(Nmod = matrix(nrow = 0, ncol = ncol(se)),
                          Nvalid = matrix(nrow = 0, ncol = ncol(se)),
                          FracMod = matrix(nrow = 0, ncol = ncol(se))),
            rowRanges = GRanges(),
            colData = colData(se),
            metadata = metadata(se))
    }

    return(seNew)
}

#' Quantify windows by calculating a Fourier-transform-based phasing score
#'
#' Calculate a phasing score by decomposing \code{FracMod} in a window into
#' frequency components and extract the \code{numCoef}-th coefficient.
#'
#' @param se A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object, as generated by \code{readModBam(..., level = "summary")}
#'     (i.e. with the assays \code{"Nvalid"} and \code{"FracMod"}).
#' @param gr A \code{\link[GenomicRanges]{GRanges}} object defining the windows
#'     to quantify. Here, the width of the ranges in \code{gr} have to be an
#'     integer multiple of the period of interest (typically
#'     \code{width(gr) = (numCoef - 1) * periodOfInterest}).
#' @param numCoef An integer scalar giving the Fourier coefficient to extract.
#'     The coefficient corresponds to a period of \code{width(gr) / (numCoef - 1)}.
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object with one row per window defined by \code{gr} and the window
#'     phasing scores for periodic signals with a frequency defined by
#'     \code{"numCoef"}.
#'     This object is suitable for transformation by
#'     \code{getRangesWithAssayValues}.
#'
#' @examples
#' library(GenomicRanges)
#' library(SummarizedExperiment)
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' rng <- GRanges("chr1", IRanges(6940000, 6943600))
#' windowStep <- 180
#' windowSize <- 4 * windowStep
#' s <- seq(start(rng), end(rng) - windowSize + 1, by = windowStep)
#' windowgr <- GRanges(seqnames = seqnames(rng),
#'                     ranges = IRanges(start = s, width = windowSize))
#' se <- readModBam(bamfiles = modbamfiles, regions = rng, level = "summary",
#'                  modbase = "a", trim = TRUE,
#'                  BPPARAM = BiocParallel::SerialParam())
#' seFourier <- phasingScoreFourier(se = se, gr = windowgr, numCoef = 5)
#' assay(seFourier, "phasingScoreAbs") # amplitude of requested coefficient
#' assay(seFourier, "phasingScoreRel") # relative amplitude
#'
#' @importFrom SummarizedExperiment rowRanges colData assay assayNames ncol
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges findOverlaps width start end
#' @importFrom S4Vectors queryHits subjectHits metadata
#' @importFrom BiocGenerics pos
#' @importFrom zoo na.approx
#' @importFrom cli cli_abort
#'
#' @export
phasingScoreFourier <- function(se, gr, numCoef = 5) {
    .assertVector(x = se, type = "RangedSummarizedExperiment")
    .assertVector(x = gr, type = "GRanges")
    .assertPackagesAvailable(pkgs = "e1071")
    if (!all(c("Nvalid", "FracMod") %in% assayNames(se))) {
        cli_abort("{.arg se} must contain assays Nvalid and FracMod")
    }
    if (!all(width(gr) == width(gr)[1])) {
        cli_abort("Not all ranges in {.arg gr} have the same width")
    }
    if (length(gr) > 0 && (width(gr)[1] %% (2 * (numCoef - 1)) > 0)) {
        cli_abort("{.code width(gr)} is not divisible by {.code 2 * (numCoef - 1)}")
    }
    period <- width(gr)[1] / (numCoef - 1)
    if (!all(diff(start(gr)) == period)) {
        cli_abort("Ranges in {.arg gr} need to be regularly spaced with a shift of {period}")
    }

    if (nrow(se) > 0 && length(gr) > 0) {
        # make sure we don't have the same position on both strands
        se <- .pruneAmbiguousStrandPositions(se, assayName = "Nvalid",
                                             verbose = FALSE)

        # loop over samples
        scoresL <- lapply(seq.int(ncol(se)), function(i) {
            # extract FracMod vector
            position <- seq(min(start(gr)), max(end(gr)))
            fracMod <- rep(NA, length(position))
            j <- pos(rowRanges(se)) %in% position
            fracMod[match(pos(rowRanges(se))[j], position)] <- assay(se, "FracMod")[j, i]
            nna <- which(!is.na(fracMod))
            if (length(nna) < length(fracMod)) {
                if (is.na(fracMod[1])) {
                    fracMod[1] <- fracMod[min(nna)]
                }
                if (is.na(fracMod[length(fracMod)])) {
                    fracMod[length(fracMod)] <- fracMod[max(nna)]
                }
            }
            fracMod <- na.approx(fracMod, na.rm = FALSE)

            # Fourier transform
            fit <- e1071::stft(X = fracMod, win = (numCoef - 1) * period,
                               inc = period, coef = ((numCoef - 1) * period) / 2,
                               wtype = "hanning.window")

            # Extract coefficient of ineterst
            list(scoreAbs = rbind(fit$values)[, numCoef],
                 scoreRel = rbind(fit$values)[, numCoef] / rowSums(rbind(fit$values)))
        })

        # construct SummarizedExperiment
        seNew <- SummarizedExperiment(
            assays = list(
                phasingScoreAbs = do.call(cbind,
                                          lapply(scoresL, "[[", "scoreAbs")),
                phasingScoreRel = do.call(cbind,
                                          lapply(scoresL, "[[", "scoreRel"))),
            rowRanges = gr,
            colData = colData(se),
            metadata = metadata(se))
    } else {
        seNew <- SummarizedExperiment(
            assays = list(
                phasingScoreAbs = matrix(nrow = 0, ncol = ncol(se)),
                phasingScoreRel = matrix(nrow = 0, ncol = ncol(se))),
            rowRanges = GRanges(),
            colData = colData(se),
            metadata = metadata(se))
    }

    return(seNew)
}


#' Quantify windows by estimating nucleosome repeat lengths (NRLs)
#'
#' Estimate nucleosome repeath length in windows using
#' \code{\link{calcModbaseSpacing}} and \code{\link{estimateNRL}}.
#'
#' @param se A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object, as generated by \code{readModBam(..., level = "quickread")}
#'     containing a read-level assay called \code{assayName}.
#' @param gr A \code{\link[GenomicRanges]{GRanges}} object defining the windows
#'     to quantify.
#' @param minperiod1,minperiod2 \code{numeric} scalars giving the smoothing
#'   parameter for de-trending the signal (minimal periods).
#' @param BPPARAM  A \code{\link[BiocParallel]{BiocParallelParam}} object that
#'     controls the number of parallel CPU threads to use for some of the steps
#'     in \code{estimateNRLwindows()}. The default value is
#'     (\code{\link[BiocParallel]{MulticoreParam}(4L)}).
#' @inheritParams calcModbaseSpacing
#' @inheritParams estimateNRL
#'
#' @author Michael Stadler
#'
#' @returns A \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}}
#'     object with one row per window defined by \code{gr} and the NRL
#'     estimates. This object is suitable for transformation by
#'     \code{getRangesWithAssayValues}.
#'
#' @examples
#' library(GenomicRanges)
#' library(SummarizedExperiment)
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' rng <- GRanges("chr1", IRanges(6930000, 6940000))
#' windowSize <- 2000
#' windowStep <- 1000
#' s <- seq(start(rng), end(rng) - windowSize + 1, by = windowStep)
#' windowgr <- GRanges(seqnames = seqnames(rng),
#'                     ranges = IRanges(start = s, width = windowSize))
#' se <- readModBam(bamfiles = modbamfiles, regions = rng, level = "quickread",
#'                  modbase = "a", trim = TRUE,
#'                  BPPARAM = BiocParallel::SerialParam())
#' seNRL <- estimateNRLwindows(se = se, gr = windowgr,
#'                             BPPARAM = BiocParallel::SerialParam())
#' assay(seNRL, "NRL")
#' assay(seNRL, "NRL.CI95low")
#' assay(seNRL, "NRL.CI95high")
#'
#' @importFrom SummarizedExperiment rowRanges colData assay assayNames ncol
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges findOverlaps
#' @importFrom S4Vectors queryHits subjectHits
#' @importFrom BiocParallel bplapply MulticoreParam
#'
#' @export
estimateNRLwindows <- function(se, gr,
                               dmax = 1000L,
                               assayName = "mod_prob",
                               minModProb = 0.5,
                               minDist = 140L,
                               usePeaks = seq_len(5),
                               minperiod1 = 30,
                               minperiod2 = 450,
                               BPPARAM = BiocParallel::MulticoreParam(4L)) {
    .assertVector(x = se, type = "RangedSummarizedExperiment")
    .assertVector(x = gr, type = "GRanges")

    if (nrow(se) > 0 && length(gr) > 0) {

        ov <- findOverlaps(query = rowRanges(se), subject = gr)
        indexL <- split(x = queryHits(ov),
                        f = factor(subjectHits(ov), levels = seq.int(length(gr))),
                        drop = FALSE)

        # loop over samples
        modprobL <- assay(se, assayName)
        s <- start(se)
        resL <- lapply(seq.int(ncol(se)), function(j) { # for each sample j
            do.call(rbind, bplapply(indexL, function(i,  # for positions i in a window
                                                     mymodprob = modprobL[[j]],
                                                     mys = s[i],
                                                     myminModProb = minModProb,
                                                     mydmax = dmax,
                                                     myminDist = minDist,
                                                     myusePeaks = usePeaks,
                                                     myminperiod1 = minperiod1,
                                                     myminperiod2 = minperiod2) {
                if (length(i) > 0) { # nocov start
                    mymodprob <- mymodprob[i, , drop = FALSE]
                    cnt <- numeric(mydmax)
                    tmp <- nnawhich(mymodprob, arr.ind = TRUE)[nnavals(mymodprob) >= myminModProb, , drop = FALSE]
                    tmp[, 1] <- mys[tmp[, 1]]
                    tmp <- split(tmp[, 1], f = tmp[, 2])
                    for (pos in tmp) {
                        calcAndCountDist(query = pos, reference = pos, cnt = cnt)
                    }

                    res <- unname(.estimateNRLfast(
                        x = cnt, minDist = myminDist, usePeaks = myusePeaks,
                        minperiod1 = myminperiod1, minperiod2 = myminperiod2))
                } else {
                    res <- rep(NA, 3L)
                }
                return(res) # nocov end
            }, BPPARAM = BPPARAM))
        })

        # construct SummarizedExperiment
        seNew <- SummarizedExperiment(
            assays = list(
                NRL = do.call(cbind, lapply(resL, "[", , 1)),
                NRL.CI95low = do.call(cbind, lapply(resL, "[", , 2)),
                NRL.CI95high = do.call(cbind, lapply(resL, "[", , 3))),
            rowRanges = gr,
            colData = colData(se)[, setdiff(colnames(colData(se)),
                                            c("n_reads", "readInfo"))],
            metadata = metadata(se))
    } else {
        seNew <- SummarizedExperiment(
            assays = list(
                NRL = matrix(nrow = 0, ncol = ncol(se)),
                NRL.CI95low = matrix(nrow = 0, ncol = ncol(se)),
                NRL.CI95high = matrix(nrow = 0, ncol = ncol(se))),
            rowRanges = GRanges(),
            colData = colData(se)[, setdiff(colnames(colData(se)),
                                            c("n_reads", "readInfo"))],
            metadata = metadata(se))
    }

    return(seNew)
}



#' Internal: core SNR estimator for one numeric vector
#'
#'
#' @importFrom stats var
#'
#' @keywords internal
#' @noRd
.estimate_snr_vec <- function(x, pos,
                              depth      = NA_real_,
                              k          = 2L,
                              min_diffs  = NULL,
                              noise_pars = NULL,
                              eps        = 1e-3) {
    
    stopifnot(length(x) == length(pos))
    
    ## need at least three data points
    if (length(x) < 3L)
        return(list(total = NA_real_, signal = NA_real_, noise = NA_real_))
    
    if (is.null(min_diffs))
        min_diffs <- max(16L, floor(0.05 * length(x)))
    ## total variance
    total_v <- var(x,na.rm=TRUE)
    
    ## parametric vs non-parametric noise estimation:
    if (!is.null(noise_pars)) {
        d_cut <- max(10,quantile(depth,0.05,na.rm = TRUE) ) # depth threshold for including depth in the model
        noise_v <- noise_pars[1] + noise_pars[2] * mean(x,na.rm=TRUE) +
            noise_pars[3] * ((depth < d_cut) / depth)  
    } else {
        ## noise variance: 0.5 * var of lag-1 differences with gap ≤ k
        gaps <- diff(pos) - 1L
        d <- diff(x)[gaps <= k]
        noise_v <- if (sum(!is.na(d)) >= min_diffs) var(d, na.rm = TRUE) / 2 else NA_real_
    }
    
    signal_v <- pmax(total_v - noise_v, eps)
    
    list(total = total_v,
         signal = signal_v,
         noise  = noise_v)
}



#' Estimate noise ~ methylation, coverage fit from randomly sampled windows
#'
#' Either
#' 1. *sample* `nWindows` windows of width `windowSize` across the chromosomes
#'    in `chromosomeLengths`, **or**
#' 2. *use* a user‑supplied set of genomic windows (`windows`).
#'
#' For every window the function retrieves per‑position *summary* data with
#' `readModBam(level = "summary")`, runs `.estimate_snr_vec()` and
#' regresses the resulting noise variances on window means and coverage.  Optionally it
#' plots the (mean, noise) cloud together with the fitted line.
#'
#' @param bamfiles Character vector with one or several modBam file names.
#'  When several files are supplied, the noise model 
#'  is fitted **independently for each sample**. The final
#'  coefficients returned are the arithmetic mean
#'  of the per-sample coefficient vectors.
#' @param modbase  Character scalar giving the modified base (as understood by
#'                 `readModBam()`).
#' @param chromosomeLengths *Named* numeric vector with chromosome sizes
#'                 (e.g. `seqlengths(BSgenome)`).  *Ignored* when `windows` is
#'                 supplied.
#' @param windowSize Integer; width of the windows (bp).  Ignored when
#'                 `windows` is supplied.
#' @param nWindows  Integer; how many windows to sample *per chromosome* in
#'                 total.  Ignored when `windows` is supplied.
#' @param k Integer (default 2L).  Two measurements are considered “adjacent”
#'   if they are at most \code{k} bases apart when estimating the noise.
#' @param windows   A `GRanges` object with *explicit* windows to analyse.  When
#'                  not `NULL`, the function uses these windows for estimation and the
#'                  arguments `chromosomeLengths`, `windowSize` and
#'                  `nWindows` are ignored.
#' @param minCov    Integer; lowest acceptable coverage in order to keep a
#'                  position.  Recommended > 1 to remove spurious positions.
#' @param plot      Logical; draw diagnostic scatter + fit.
#' @param BPPARAM   A `BiocParallelParam` object (set an `RNGseed` for
#'                  reproducibility).
#'
#' @return Numeric vector `c(intercept = a, slopeMean = b, slopeInvDepth = c)`
#'         suitable for `snrScoreWindows()` (store it in
#'         `metadata(se)$NoisePars`).
#'
#' @author Panagiotis Papasaikas
#'
#' @examples
#' library(GenomicRanges)
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' gr0 <- GRanges("chr1", IRanges(6920000, 6950000))
#' gr_tiles <- unlist(tile(gr0, width = 500))
#' gr_tiles
#' coef <- estimateNoiseParsWindows(modbamfiles,modbase="a",windows=gr_tiles, plot=TRUE)
#' 
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges IRanges findOverlaps
#' @importFrom SummarizedExperiment assay assayNames
#' @importFrom S4Vectors queryHits subjectHits
#' @importFrom stats coef lm quantile
#' @importFrom dplyr between
#' @importFrom cli cli_abort
#' @importFrom BiocGenerics pos
#' @importFrom grDevices colorRampPalette
#' @importFrom BiocParallel MulticoreParam
#'
#' @export
estimateNoiseParsWindows <- function(bamfiles,
                                     modbase,
                                     chromosomeLengths = NULL,
                                     windowSize = 500L,
                                     nWindows   = 500L,
                                     k = 2L,
                                     minCov     = 3L,
                                     windows    = NULL,
                                     plot       = FALSE,
                                     BPPARAM    = BiocParallel::MulticoreParam(
                                         4L, RNGseed = 42L)) {
    .assertVector(bamfiles, "character")
    .assertScalar(modbase,  "character")
    .assertScalar(k,         "numeric", rngIncl = c(1L, Inf))
    if (is.null(windows)) {
        # sample* windows 
        .assertVector(chromosomeLengths, "numeric")
        .assertScalar(windowSize,        "numeric", rngExcl = c(0, Inf))
        .assertScalar(nWindows,          "numeric", rngExcl = c(10, Inf))
        if (is.null(names(chromosomeLengths)) ||
            anyDuplicated(names(chromosomeLengths)))
            cli_abort("{.arg chromosomeLengths} must be a *named* vector.")
        
        
        seqnamesToSampleFrom <- names(chromosomeLengths)
    } else {
        # *use* explicit windows 
        .assertVector(windows, "GRanges")
        winGR <- windows              # keep original order/names
        if (length(winGR) == 0)
            return(setNames(rep(NA_real_, 3),
                            c("intercept", "slopeMean", "slopeInvDepth")))
    }
    
    .assertScalar(minCov,  "numeric", rngExcl = c(1, Inf))
    .assertScalar(plot,    "logical")
    
    ## 1. obtain (or sample) windows 
    if (is.null(windows)) {
        nPerChr <- ceiling(nWindows / length(seqnamesToSampleFrom))
        starts  <- lapply(seqnamesToSampleFrom, function(chr) {
            maxStart <- chromosomeLengths[chr] - windowSize + 1L
            if (maxStart < 1L) return(integer(0))
            sample.int(maxStart, nPerChr, replace = TRUE)
        })
        winGR <- GRanges(seqnames = rep(seqnamesToSampleFrom, each = nPerChr),
                         ranges   = IRanges(unlist(starts), width = windowSize))
        winGR <- winGR[seq_len(min(length(winGR), nWindows))]
    }
    
    ## 2. fetch per-position summary data
    sePos <- readModBam(bamfiles = bamfiles,
                        regions  = winGR,
                        modbase  = modbase,
                        level    = "summary",
                        trim     = TRUE,
                        BPPARAM  = BPPARAM) |>
        filterPositions(filters="coverage",
                        minCov=minCov, assayNameNA=NULL,
                        minNbrSamples=length(bamfiles))
    
    if (!all(c("FracMod","Nvalid","Nmod") %in% assayNames(sePos)))
        return(setNames(rep(NA_real_,3),
                        c("intercept","slopeMean","slopeInvDepth")))
    
    ov   <- findOverlaps(rowRanges(sePos), winGR, ignore.strand = TRUE)
    idxL <- split(queryHits(ov),
                  factor(subjectHits(ov), levels = seq_along(winGR)), drop=FALSE)
    
    POS <- pos(rowRanges(sePos)) # genomic coordinates
    FM <- assay(sePos, "FracMod")              # nPos × nSam
    NV <- assay(sePos, "Nvalid")
    
    # per-sample regressions
    nWin <- length(winGR)
    nSam <- ncol(sePos)
    
    meanMat  <- noiseMat <- depthMat <-
        matrix(NA_real_, nrow = nWin, ncol = nSam,
               dimnames = list(NULL, colnames(sePos)))
    
    coefMat <- matrix(NA_real_, nrow = 3, ncol = nSam,
                      dimnames = list(c("intercept",
                                        "slopeMean",
                                        "slopeInvDepth"),
                                      colnames(sePos)))
    

    for (j in seq_len(nSam)) {
        
        meanVals <- noiseVals <- depthVals <- numeric(nWin)
        
        for (w in seq_along(idxL)) {
            ii   <- idxL[[w]]
            vec  <- FM[ii, j]
            dep  <- median(NV[ii, j])
            offs <- POS[ii] - start(winGR)[w] + 1L
            
            est  <- .estimate_snr_vec(vec, pos = offs, depth = dep, k = k)
            
            meanVals [w] <- mean(vec,  na.rm = TRUE)
            noiseVals[w] <- est$noise
            depthVals[w] <- dep
        }
        
        #depth threshold for including depth in the model
        d_cut <- max(10,quantile(depthVals,0.05,na.rm = TRUE) )
        
        # keep / filter 
        keep <- is.finite(meanVals)  & is.finite(noiseVals) &
            is.finite(depthVals) & depthVals > 0
        qMean  <- quantile(meanVals [keep], c(0.05, 0.99))
        qDepth <- quantile(depthVals[keep], c(0.01, 0.95))
        qNoise <- quantile(noiseVals[keep]/(meanVals[keep]+0.01), c(0.01, 0.7) )
        keep <- keep &
            between(meanVals , qMean [1], qMean [2]) &
            between(depthVals, qDepth[1], qDepth[2]) &
            between(noiseVals/(meanVals+0.01), qNoise[1], qNoise[2])
        
        if (sum(keep) >= 10) {
            z <- ifelse(depthVals[keep] <= d_cut, 1 / depthVals[keep], 0)
            coefMat[, j] <- coef(
                lm(noiseVals[keep] ~ meanVals[keep] + z ))
        }
        
        # store stats for plotting
        meanMat [keep, j] <- meanVals[keep]
        noiseMat[keep, j] <- noiseVals[keep]
        depthMat[keep, j] <- depthVals[keep]
    }

    # Average per sample coefficients:
    cf  <- setNames(rowMeans(coefMat, na.rm = TRUE),
                    c("intercept","slopeMean","slopeInvDepth"))
    
    ##  Plotting
    if (plot) {
        par(mfrow = c(nSam, 2))
        op <- par(mar = c(4, 4, 0.5, 0.5)); on.exit(par(op))
        
        for (j in seq_len(nSam)) {
            
            meanVals  <- meanMat [, j]
            noiseVals <- noiseMat[, j]
            depthVals <- depthMat[, j]

            ## colour maps 
            cols_depth <- colorRampPalette(c("navy", "gold"))(100)[
                cut(depthVals, 100)]
            cols_mean  <- colorRampPalette(c("navy", "gold"))(100)[
                cut(meanVals, 100)]
            
            ## global fitted lines
            avgInvDepth <- mean(1 / depthVals, na.rm=TRUE)
            avgMean     <- mean(meanVals, na.rm=TRUE)
            
            int1 <- cf["intercept"] + cf["slopeInvDepth"] * avgInvDepth
            slo1 <- cf["slopeMean"]
            int2 <- cf["intercept"] + cf["slopeMean"] * avgMean
            slo2 <- cf["slopeInvDepth"]
            
            ## panel 1: noise ~ mean
            plot(meanVals, noiseVals,
                 pch = 19, col = cols_depth,
                 main = colnames(sePos)[j],
                 xlab = "Window meanmod.", ylab = "Noise variance")
            abline(a = int1, b = slo1, lwd = 2); grid()
            
            ## panel 2: noise ~ 1/coverage
            plot(1 / depthVals, noiseVals,
                 pch = 19, col = cols_mean,
                 xlab = "1/Window coverage", ylab = "Noise variance")
            abline(a = int2, b = slo2, lwd = 2); grid()
        }
    }
    return(cf)
}






#' Quantify windows by estimating total, signal and noise variance (SNR)
#'
#' For each genomic window in \code{gr} the function aggregates a continuous
#' per-position assay (default \code{"FracMod"}) and estimates
#' (i) total variance, (ii) noise variance
#' and (iii) signal variance as \code{total - noise}.  
#' The \eqn{\log_2(\text{signal}/\text{noise})} is returned as SNR.
#'
#' @param se A per-position \code{RangedSummarizedExperiment}, typically the
#'   output of \code{readModBam(..., level = "summary")}.
#'   Must contain the assay given by \code{assayNameAgg} and an assay
#'   \code{"Nvalid"} with coverage.
#' @param gr \code{GRanges} specifying the windows.
#' @param assayNameAgg Character scalar, assay to aggregate (default
#'   \code{"FracMod"}).
#' @param k Integer (default 2L).  Two measurements are considered “adjacent”
#'   if they are at most \code{k} bases apart when estimating the noise.
#' @param min_diffs Integer or \code{NULL}.  Minimal number of paired
#'   differences to compute a reliable noise estimate.  If \code{NULL} the
#'   value is set to \code{max(16, floor(0.05 * n))}, where \code{n} is the
#'   number of valid positions in the window.
#' @param noise_pars Numeric vector as returned by
#'   \code{estimateNoiseParsWindows()}.  If \code{NULL} the function looks
#'   for \code{metadata(se)$NoisePars}.  If still \code{NULL} raw noise estimates are used
#' @details
#' Noise variance estimation can be performed in two ways:
#'
#' 1. **Parametric estimation**:  
#'    If noise parameters (`noise_pars`) are supplied (typically estimated using 
#'    \code{estimateNoiseParsWindows()}, which fits a linear regression model to 
#'    relate noise variance to average methylation level and coverage across random genomic windows), 
#'    the noise variance returned is the expected noise given the window's average methylation 
#'    and coverage.
#'
#' 2. **Non-parametric (raw) estimation**:  
#'    If noise parameters are not supplied, the function estimates noise directly from the data, 
#'    based on short-range variation between neighboring positions. While unbiased for random signals, 
#'    this method can *overestimate* noise—and thus underestimate the true SNR—if the biological signal 
#'    is strongly correlated across reads (e.g., due to systematic accessibility patterns), because the 
#'    structured variation is incorrectly interpreted as random noise.
#'    
#' @seealso \code{\link{estimateNoiseParsWindows}} for estimation of the global noise model parameters.
#' 
#' @return A \code{SummarizedExperiment} with assays
#'   \code{"TotalVar"}, \code{"SignalVar"}, \code{"NoiseVar"} and
#'   \code{"SNR"} (\eqn{\log_2} signal/noise).
#'
#' @author Panagiotis Papasaikas
#'
#' @examples
#' library(GenomicRanges)
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' gr0 <- GRanges("chr1", IRanges(6920000, 6950000))
#' gr_tiles <- unlist(tile(gr0, width = 500))
#' gr_tiles
#' #Estimate noise parameters (typically should be performed on a larger, independent sample of genomic windows)
#' coef <- estimateNoiseParsWindows(modbamfiles,modbase="a",windows=gr_tiles, plot=TRUE)
#'
#' se <- readModBam(bamfiles = modbamfiles,
#'                    regions  = gr_tiles,
#'                    modbase  = "a",
#'                    level    = "summary",
#'                    trim     = TRUE) |>
#'    filterPositions(filters="coverage",
#'                    minCov=2, assayNameNA=NULL) 
#' se_snr_scores1 <- snrScoreWindows(se, gr = gr_tiles,noise_pars = coef) # parametric noise estimation 
#' se_snr_scores2 <- snrScoreWindows(se, gr = gr_tiles) # non-parametric noise estimation
#'
#' @importFrom SummarizedExperiment assay assayNames SummarizedExperiment colData
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges findOverlaps
#' @importFrom S4Vectors queryHits subjectHits metadata
#' @importFrom BiocGenerics pos
#' @export
snrScoreWindows <- function(se, gr,
                            assayNameAgg = "FracMod",
                            k = 2L,
                            min_diffs    = NULL,
                            noise_pars   = NULL) {
    .assertVector(se, "RangedSummarizedExperiment")
    .assertVector(gr, "GRanges")
    .assertScalar(assayNameAgg, "character", validValues = assayNames(se))
    
    if (!"Nvalid" %in% assayNames(se))
        cli::cli_abort("{.arg se} must contain an assay {.code Nvalid}.")
    .assertScalar(k,         "numeric", rngIncl = c(1L, Inf))
    if (!is.null(min_diffs)) .assertScalar(min_diffs, "numeric", rngIncl=c(1L,Inf))
    
    if (!is.null(noise_pars))
        .assertVector(noise_pars, "numeric", len = 3)
    if (is.null(noise_pars) && !is.null(metadata(se)$NoisePars))
        noise_pars <- metadata(se)$NoisePars
    
    
    # empty input
    if (nrow(se) == 0 || length(gr) == 0) {
        return(SummarizedExperiment(
            assays    = list(
                TotalVar = matrix(nrow = 0, ncol = ncol(se)),
                SignalVar = matrix(nrow = 0, ncol = ncol(se)),
                NoiseVar  = matrix(nrow = 0, ncol = ncol(se)),
                SNR       = matrix(nrow = 0, ncol = ncol(se))),
            rowRanges = GRanges(),
            colData   = colData(se),
            metadata  = metadata(se)))
    }
    
    # overlaps 
    ov   <- findOverlaps(rowRanges(se), gr, ignore.strand = TRUE)
    idxL <- split(queryHits(ov),
                  factor(subjectHits(ov), levels = seq_len(length(gr))),
                  drop = FALSE)
    
    nWin <- length(gr); nSam <- ncol(se)
    totMat <-  matrix(NA_real_, nrow = nWin, ncol = nSam)
    
    rowNames <- if (is.null(names(gr))) {
        as.character(seq_len(nWin))
    } else {
        names(gr)
    }
    
    dimnames(totMat) <- list(rowNames, colnames(se))
    
    sigMat <- noiseMat <- snrMat <- totMat
    
    
    signal  <- assay(se, assayNameAgg)
    depth   <- assay(se, "Nvalid")
    posVec  <- pos(rowRanges(se))
    
    # main loop
    for (j in seq_len(nSam)) {
        resL <- lapply(seq_len(nWin), function(w) {
            ii <- idxL[[w]]
            if (length(ii) < 3L)
                return(list(total = NA_real_, signal = NA_real_, noise = NA_real_))
            
            x    <- signal[ii, j]
            offs <- posVec[ii] - start(gr)[w] + 1L
            dep  <- median(depth[ii, j])
            
            .estimate_snr_vec(x, pos = offs,
                              depth      = dep,
                              k          = k,
                              min_diffs  = min_diffs,
                              noise_pars = noise_pars,
                              eps=1e-3)
        })
        
        totMat[, j]   <- vapply(resL, `[[`, numeric(1), "total")
        sigMat[, j]   <- vapply(resL, `[[`, numeric(1), "signal")
        noiseMat[, j] <- vapply(resL, `[[`, numeric(1), "noise")
        snrMat[, j]   <- log2(sigMat[, j] / pmax(noiseMat[, j],1e-3) )
    }
    
    #  return 
    SummarizedExperiment(
        assays = list(
            TotalVar = totMat,
            SignalVar = sigMat,
            NoiseVar  = noiseMat,
            SNR       = snrMat),
        rowRanges = gr,
        colData   = colData(se),
        metadata  = c(metadata(se),
                      list(NoisePars = noise_pars,
                           k            = k,
                           min_diffs    = min_diffs)))
}









#' Generate counts for sequential windows in a single region
#'
#' Read modification data from \code{bamfiles} for a chunk of the genome
#' defined by \code{region} (by calling \code{\link{readModBam}} and aggregate
#' modified and total counts for windows.
#'
#' @param bamfiles Character vector with one or several modBam file names.
#'     Note that no read-filtering will be performed on the data from
#'     these files, so possibly the files should contain only filtered
#'     alignments.
#' @param region A \code{\link[GenomicRanges]{GRanges}} object specifying which
#'     genomic region to extract the reads from. Alternatively, the regions can
#'     be specified as a character scalar (e.g. "chr1:1200-1300") that can be
#'     coerced into a \code{GRanges} object.
#' @param modbase Character vector defining the modified base to extract.
#' @param level A character scalar giving the level of the data to
#'     required by \code{quantFunction} (see \code{\link{readModBam}}).
#' @param modProbThreshold A numeric scalar, indicating the modification
#'     probability threshold to use to classify a base as 'modified' or
#'     'unmodified'.
#' @param sampleAnnot A \code{data.frame} (or \code{NULL}) providing annotations
#'     for the samples. It must contain at least one column, named
#'     \code{"sample"}, which must contain all the values of
#'     \code{names(bamfiles)}. The provided annotations will be propagated to
#'     the returned \code{SummarizedExperiment} object.
#' @param seqinfo \code{NULL} or a \code{\link[GenomeInfoDb]{Seqinfo}} object
#'     containing information about the set of genomic sequences (chromosomes).
#'     Alternatively, a named numeric vector with genomic sequence names and
#'     lengths. Useful to set the sorting order of sequence names.
#' @param sequenceContextWidth,sequenceReference Define the sequence
#'     context to be extracted around modified bases. By default (
#'     \code{sequenceContextWidth = 0}), no sequence context will be
#'     extracted, otherwise it will be returned in \code{rowData(x)$sequenceContext}.
#'     See \code{\link{addSeqContext}} for details.
#' @param sequenceContext A character vector with sequence contexts to
#'     retain. To apply this filter, the arguments \code{"sequenceContextWidth"}
#'     and \code{"sequenceReference"} must be set.
#' @param windowMode Character scalar defining how windows in \code{region}
#'     are define. Currently supported are:
#'     \describe{
#'         \item{"fixed"}{: The window is of fixed size (in number of bases),
#'         corresponding to the \code{windowSize} argument value.}
#'         \item{"predefined"}{: The windows are provided by the user, as
#'         a \code{\link[GenomicRanges]{GRanges}} object.}
#'     }
#' @param windowSize Numeric scalar defining the size of windows (see
#'     \code{windowMode} argument).
#' @param windowStep Numeric scalar defining the step (shift) between
#'     start positions of consecutive windows. For non-overlapping
#'     consecutive windows, \code{windowStep} should be equal to
#'     \code{windowSize}.
#' @param windows \code{\link[GenomicRanges]{GRanges}} object with pre-defined
#'     windows (if \code{windowMode = "predefined"}). Only windows where the
#'     midpoint overlaps \code{region} will be considered.
#' @param quantFunction A character scalar giving the name of the window
#'     quantification function. This function should take as a first argument a
#'     \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}} object, as
#'     generated by \code{readModBam}. The second argument should be a
#'     \code{\link[GenomicRanges]{GRanges}} object defining the windows to
#'     quantify. Additional arguments may be passed to \code{quantFunction}
#'     using \code{quantFunctionArgs}. The function must return a
#'     \code{\link[SummarizedExperiment]{RangedSummarizedExperiment}} object
#'     with one row per window defined by the second argument and the window
#'     quantifications contained in the assay(s).
#' @param quantFunctionArgs List with additional arguments for \code{quantFunction}.
#' @param BPPARAM A \code{\link[BiocParallel]{BiocParallelParam}} object that
#'     controls the number of parallel CPU threads to use for some of the steps
#'     in \code{readModBam()}. The default value is
#'     (\code{\link[BiocParallel]{MulticoreParam}(4L, RNGseed = 42L)}).
#'     If randomly sampling reads (\code{nAlnsToSample > 0}), make sure to set
#'     the \code{RNGseed} argument when constructing the \code{BPPARAM} object
#'     for reproducible results (see also
#'     \code{vignette("Random_Numbers", package = "BiocParallel")}).
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @author Panagiotis Papasaikas, Sebastien Smallwood, Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[SummarizedExperiment]{SummarizedExperiment}} object
#'     with columns corresponding to samples (the elements of \code{bamfiles})
#'     and rows corresponding to windows in \code{region}. The object contains
#'     the assays \code{"Nmod"} and \code{"Nvalid"} containing the number of
#'     modified and total (valid) bases in each window and sample, respectively.
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' gnmfasta <- system.file("extdata", "reference.fa.gz", package = "footprintR")
#' quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                         region = "chr1:6940000-6955000",
#'                         modbase = "a",
#'                         sequenceContextWidth = 1,
#'                         sequenceReference = gnmfasta,
#'                         sequenceContext = "A",
#'                         BPPARAM = BiocParallel::SerialParam())
#' quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                         region = "chr1:6940000-6955000",
#'                         modbase = "a",
#'                         BPPARAM = BiocParallel::SerialParam())
#'
#' @importFrom SummarizedExperiment colData
#' @importFrom GenomicRanges GRanges GPos
#' @importFrom IRanges IRanges start end findOverlaps overlapsAny
#' @importFrom S4Vectors queryHits subjectHits metadata
#' @importFrom cli cli_abort
#' @importFrom BiocParallel MulticoreParam
#'
#' @export
quantifyWindowsInRegion <- function(bamfiles,
                                    region,
                                    modbase,
                                    level = "summary",
                                    modProbThreshold = 0.5,
                                    sampleAnnot = NULL,
                                    seqinfo = NULL,
                                    sequenceContextWidth = 0,
                                    sequenceReference = NULL,
                                    sequenceContext = NULL,
                                    windowMode = "fixed",
                                    windowSize = 24,
                                    windowStep = round(windowSize / 2),
                                    windows = NULL,
                                    quantFunction = "sumNmodNvalid",
                                    quantFunctionArgs = list(),
                                    BPPARAM = MulticoreParam(4L, RNGseed = 42L),
                                    verbose = FALSE) {
    # check parameters
    if (is.character(region)) {
        region <- .regionStringToGRanges(region, seqinfo = seqinfo)
    }
    if (windowMode == "predefined") {
        .assertVector(x = region, type = "GRanges")
    } else {
        .assertScalar(x = region, type = "GRanges")
    }
    .assertScalar(x = modbase, type = "character")
    .assertScalar(x = windowMode, type = "character",
                  validValues = c("fixed", "predefined"))
    if (windowMode == "fixed") {
        .assertScalar(x = windowSize, type = "numeric", rngIncl = c(1L, Inf))
        .assertScalar(x = windowStep, type = "numeric", rngIncl = c(1L, Inf))
    } else if (windowMode == "predefined") {
        .assertVector(x = windows, type = "GRanges")
    }
    .assertScalar(x = quantFunction, type = "character")
    if (!exists(quantFunction)) {
        cli_abort("{.arg quantFunction} must be the name of an existing function")
    }

    # read summary-level data
    se <- readModBam(bamfiles = bamfiles, regions = region, modbase = modbase,
                     level = level, sampleAnnot = sampleAnnot,
                     seqinfo = seqinfo,
                     sequenceContextWidth = sequenceContextWidth,
                     sequenceReference = sequenceReference,
                     modProbThreshold = modProbThreshold,
                     trim = TRUE, BPPARAM = BPPARAM,
                     verbose = verbose)

    # filter positions
    if (!is.null(sequenceContext)) {
        se <- filterPositions(se = se, filters = "sequenceContext",
                              sequenceContext = sequenceContext,
                              assayNameNA = NULL)
    }

    # define windows for aggregation
    if (nrow(se) > 0) {
        if (identical(windowMode, "fixed")) {
            s <- seq(start(region), end(region) - windowSize + 1,
                     by = windowStep)
            windowgr <- GRanges(seqnames = seqnames(region),
                                ranges = IRanges(start = s,
                                                 width = windowSize))
        } else if (identical(windowMode, "predefined")) {
            windowgr <- windows[overlapsAny(
                resize(windows, width = 1, fix = "center"),
                region, ignore.strand = TRUE)]
        }
    } else {
        windowgr <- GRanges()
    }

    # quantify windows using quantFunction
    seNew <- do.call(quantFunction, c(list(quote(se), quote(windowgr)),
                                      quantFunctionArgs))

    return(seNew)
}


#' Analyze counts for sequential windows in a single region
#'
#' Given a \code{SummarizedExperiment} with modified and total
#' base counts in assays \code{"Nmod"} and \code{"Nvalid"},
#' perform a pairwise statistical test for differential modification.
#'
#' @param se \code{SummarizedExperiment}, for example returned by
#'     \code{quantifyWindowsInRegion}. It is expected to at least
#'     contain assays for modified and total counts (given by
#'     \code{assayNameMod} and \code{assayNameValid}) and
#'     a \code{colData} column that defines the groups (given
#'     by \code{groupCol}).
#' @param assayNameMod,assayNameValid Character scalars that give
#'     the assay names in \code{se} containing the modified and
#'     total counts, respectively.
#' @param groupCol Character scalar giving the column in \code{colData(se)}
#'     that defines the groups of samples to be compared.
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @author Panagiotis Papasaikas, Sebastien Smallwood, Charlotte Soneson, Michael Stadler
#'
#' @returns The \code{\link[GenomicRanges]{GRanges}} object constructed from
#'     the \code{\link[edgeR]{topTags}} output obtained for the statistical
#'     analysis, with additional columns for the average fraction modified
#'     counts in each group, and summary columns named "dirNegLog10PValue" (the
#'     sign of the logFC multiplied with the -log10(PValue)) and "DeltaFracMod"
#'     (the difference of the average modification fraction in the two groups).
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_1_10reads.bam",
#'                              "6mA_2_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' se <- quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                               region = "chr1:6940000-6955000", modbase = "a",
#'                               BPPARAM = BiocParallel::SerialParam())
#' se$group <- c("group1", "group1", "group2", "group2")
#' gr <- getDifferentiallyModifiedWindows(se, groupCol = "group", verbose = TRUE)
#' class(gr)
#' head(gr)
#'
#' @importFrom SummarizedExperiment assayNames colData assay ncol
#' @importFrom GenomicRanges GRanges
#' @importFrom S4Vectors mcols<- DataFrame
#' @importFrom stats model.matrix
#' @importFrom methods as
#' @importFrom cli cli_abort
#'
#' @export
getDifferentiallyModifiedWindows <- function(se,
                                             assayNameMod = "Nmod",
                                             assayNameValid = "Nvalid",
                                             groupCol = "group",
                                             verbose = FALSE) {
    # check arguments
    .assertVector(x = se, type = "SummarizedExperiment")
    .assertScalar(x = assayNameMod, type = "character",
                  validValues = assayNames(se))
    .assertScalar(x = assayNameValid, type = "character",
                  validValues = assayNames(se))
    .assertScalar(x = groupCol, type = "character",
                  validValues = colnames(colData(se)))
    if (length(unique(colData(se)[[groupCol]])) != 2) {
        cli_abort(paste0(
            "The group column in {.code colData(se)} ({groupCol}) ",
            "needs to have exactly two unique values."))
    }
    levs <- levels(factor(colData(se)[[groupCol]]))
    .assertScalar(x = verbose, type = "logical")
    .assertPackagesAvailable(pkgs = "edgeR")

    if (nrow(se) > 0) {
        # calculate library size and unmodified counts
        .message("calculating library sizes and normalization factors")
        libsizes <- colSums(assay(se, assayNameValid))
        nfacts <- edgeR::normLibSizes(assay(se, assayNameValid))
        cnt <- cbind(assay(se, assayNameMod),
                     assay(se, assayNameValid) - assay(se, assayNameMod))
        cd2 <- cbind(rbind(colData(se)[, c("sample", groupCol)],
                           colData(se)[, c("sample", groupCol)]),
                     data.frame(type = rep(c("mod", "unmod"), each = ncol(se))))
        cd2$group <- factor(cd2$group)

        # create design matrix
        .message("creating design matrix")
        dsgn <- model.matrix(~ 0 + sample, data = cd2)
        for (grp in levels(cd2$group)) {
            dsgn <- cbind(dsgn, cd2$group == grp & cd2$type == "mod")
        }
        colnames(dsgn)[ncol(dsgn) - c(1, 0)] <- levels(cd2$group)
        rownames(cnt) <- NULL
        colnames(cnt) <- rownames(dsgn) <- paste0(rep(colnames(se), 2),
                                                  rep(c(".mod", ".unmod"),
                                                      each = ncol(se)))

        # test for differential modification
        .message("testing for differential modifications ({levels(cd2$group)[2]} - {levels(cd2$group)[1]})")
        dgeL <- edgeR::DGEList(counts = cnt, lib.size = rep(libsizes, 2),
                               norm.factors = rep(nfacts, 2),
                               genes = as.data.frame(unname(rowRanges(se))))
        dgeL <- edgeR::estimateDisp(y = dgeL, design = dsgn)
        fit <- edgeR::glmFit(y = dgeL, design = dsgn)
        tst <- edgeR::glmLRT(
            glmfit = fit,
            contrast = (colnames(dsgn) == levels(cd2$group)[2]) -
                (colnames(dsgn) == levels(cd2$group)[1]))

        # coerce topTags to GRanges
        tt <- edgeR::topTags(object = tst, n = Inf, sort.by = "none")
        tt$table$dirNegLog10PValue <- sign(tt$table$logFC) * -log10(tt$table$PValue)
        gr <- as(tt$table, "GRanges")
    } else {
        gr <- GRanges()
        mcols(gr) <- DataFrame(logFC = numeric(0),
                               logCPM = numeric(0),
                               LR = numeric(0),
                               PValue = numeric(0),
                               FDR = numeric(0),
                               dirNegLog10PValue = numeric(0))
    }

    # add fracmod and deltafracmod
    FracMod <- assay(se, assayNameMod) / assay(se, assayNameValid)
    for (i in c(1, 2)) {
        mcols(gr)[[paste0("FracMod_", levs[i])]] <-
            rowMeans(FracMod[, se[[groupCol]] == levs[i], drop = FALSE])
    }
    mcols(gr)[["DeltaFracMod"]] <-
        mcols(gr)[[paste0("FracMod_", levs[2])]] -
        mcols(gr)[[paste0("FracMod_", levs[1])]]
    return(gr)
}

#' Perform differential analysis on the rows of an assay
#'
#' Given a \code{SummarizedExperiment} with at least one assay, use either
#' the likelihood ratio framework of \code{edgeR} or the linear model
#' framework of \code{limma} to fit a model for each row of the specified
#' assay and extract statistics corresponding to a specific contrast.
#'
#' @param se \code{SummarizedExperiment}, for example returned by
#'     \code{phasingScoreFourier}.
#' @param assayName Character scalar that gives the assay name in \code{se}
#'     containing the values to test.
#' @param designMatrix Numeric matrix providing the design matrix for the
#'     statistical modeling. Must have row names, corresponding to the sample
#'     (column) names of \code{se}.
#' @param contrast Numeric vector providing the contrast to test.
#' @param method Character scalar giving the method to use. Currently
#'     supported methods are "edgeR" and "limma".
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @author Charlotte Soneson
#'
#' @returns The \code{\link[GenomicRanges]{GRanges}} object constructed from
#'     the \code{\link[edgeR]{topTags}} or \code{\link[limma]{topTable}} output
#'     obtained for the statistical analysis, with an additional summary column
#'     named "dirNegLog10PValue" (the sign of the logFC multiplied with the
#'     -log10(PValue)).
#'
#' @examples
#' library(GenomicRanges)
#' library(SummarizedExperiment)
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_1_10reads.bam",
#'                              "6mA_2_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' rng <- GRanges("chr1", IRanges(6940000, 6943600))
#' windowStep <- 180
#' windowSize <- 4 * windowStep
#' s <- seq(start(rng), end(rng) - windowSize + 1, by = windowStep)
#' windowgr <- GRanges(seqnames = seqnames(rng),
#'                     ranges = IRanges(start = s, width = windowSize))
#' se <- readModBam(bamfiles = modbamfiles, regions = rng, level = "summary",
#'                  modbase = "a", trim = TRUE,
#'                  BPPARAM = BiocParallel::SerialParam())
#' seFourier <- phasingScoreFourier(se = se, gr = windowgr, numCoef = 5)
#' seFourier$group <- c("group1", "group1", "group2", "group2")
#' mm <- model.matrix(~ group, data = colData(seFourier))
#' gr <- getDifferentialWindows(seFourier, assayName = "phasingScoreAbs",
#'                              designMatrix = mm,
#'                              contrast = c(0, 1),
#'                              method = "limma",
#'                              verbose = TRUE)
#' class(gr)
#' head(gr)
#'
#' @importFrom SummarizedExperiment assayNames assay rowRanges
#' @importFrom GenomicRanges GRanges
#' @importFrom S4Vectors mcols<- DataFrame
#' @importFrom methods as
#' @importFrom cli cli_abort
#'
#' @export
getDifferentialWindows <- function(se,
                                   assayName = "phasingScoreAbs",
                                   designMatrix,
                                   contrast,
                                   method = "limma",
                                   verbose = FALSE) {
    # check arguments
    .assertVector(x = se, type = "SummarizedExperiment")
    .assertScalar(x = assayName, type = "character",
                  validValues = assayNames(se))
    .assertVector(x = designMatrix, type = "matrix")
    .assertVector(x = rownames(designMatrix), type = "character")
    stopifnot(all(rownames(designMatrix) == colnames(se)))
    .assertVector(x = contrast, type = "numeric", len = ncol(designMatrix))
    .assertScalar(x = verbose, type = "logical")
    .assertScalar(x = method, type = "character",
                  validValues = c("edgeR", "limma"))
    .assertPackagesAvailable(pkgs = method)

    if (nrow(se) > 0) {
        if (method == "edgeR") {
            dgeL <- edgeR::DGEList(counts = assay(se, assayName),
                                   genes = as.data.frame(unname(rowRanges(se))))
            dgeL <- edgeR::estimateDisp(y = dgeL, design = designMatrix)
            fit <- edgeR::glmFit(y = dgeL, design = designMatrix)
            tst <- edgeR::glmLRT(
                glmfit = fit,
                contrast = contrast
            )

            # coerce topTags to GRanges
            tt <- edgeR::topTags(object = tst, n = Inf, sort.by = "none")
            tt$table$dirNegLog10PValue <-
                sign(tt$table$logFC) * -log10(tt$table$PValue)
            gr <- as(tt$table, "GRanges")
        } else {
            fit <- limma::lmFit(object = assay(se, assayName),
                                design = designMatrix)
            fit <- limma::contrasts.fit(fit, contrast = contrast)
            fit <- limma::eBayes(fit)

            # coerce topTable to GRanges
            tt <- limma::topTable(fit, number = Inf, sort.by = "none")
            tt$dirNegLog10PValue <-
                sign(tt$logFC) * -log10(tt$P.Value)
            gr <- as(cbind(as.data.frame(unname(rowRanges(se))), tt), "GRanges")
        }
    } else {
        gr <- GRanges()
        mcols(gr) <- DataFrame(logFC = numeric(0),
                               AveExpr = numeric(0),
                               t = numeric(0),
                               P.Value = numeric(0),
                               adj.P.Val = numeric(0),
                               B = numeric(0),
                               dirNegLog10PValue = numeric(0))
    }
    return(gr)
}

#' Create a \code{GRanges} from a \code{SummarizedExperiment}.
#'
#' Create a \code{GRanges} object from \code{rowRanges} and \code{assay} of
#' a \code{SummarizedExperiment} object.
#'
#' @param se \code{RangedSummarizedExperiment} object, for example returned by
#'     \code{quantifyWindowsInRegion}.
#' @param assayName Character scalar defining the assay to be extracted from
#'     \code{se} and set as \code{mcols(...)} of the return value. Thus, each
#'     column of the assay will become a column in \code{mcols(...)}.
#'     If missing, the first assay from \code{se} will be used.
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[GenomicRanges]{GRanges}} object, with the selected
#'     assay in its metadata columns.
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_1_10reads.bam",
#'                              "6mA_2_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' se <- quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                               region = "chr1:6940000-6955000", modbase = "a",
#'                               BPPARAM = BiocParallel::SerialParam())
#' gr <- getRangesWithAssayValues(se, assayName = "Nmod")
#' gr
#'
#' @importFrom SummarizedExperiment rowRanges assay assayNames colnames
#' @importFrom S4Vectors mcols<-
#'
#' @export
getRangesWithAssayValues <- function(se, assayName) {
    .assertVector(x = se, type = "RangedSummarizedExperiment")
    if (missing(assayName)) {
        assayName <- assayNames(se)[1]
    }
    .assertVector(x = assayName, type = "character",
                  validValues = assayNames(se))

    gr <- rowRanges(se)
    for (an in assayName) {
        tmp <- assay(se, an)
        colnames(tmp) <- paste0(an, ".", colnames(se))
        mcols(gr) <- cbind(mcols(gr), tmp)
    }

    return(gr)
}

#' Process scores of sequential genomic windows.
#'
#' Given scores or statistical estimates for sequential windows,
#' process them according to the \code{scoreAction} argument.
#' Typical actions are to smooth the scores and possibly identify
#' regions of interest by fusing consistent neighboring windows
#' along the genome.
#'
#' @param x \code{GRanges} object with window-based scores or estimates.
#'     Ranges correspond to windows, and columns in \code{mcols(x)} to scores.
#' @param scoreCol Character scalar giving the column name in \code{mcols(x)}
#'     to use for the analysis. For \code{scanForHighScoringRegions}, it can
#'     be a vector, in which case \code{processWindowScores} will be run for
#'     each of them and the results will be returned as a list.
#' @param scoreAction A character scalar indicating how to process the
#'     scores. Currently supported values are:
#'     \describe{
#'         \item{pass}{: Do not modify window scores (pass-through). Note that
#'             if \code{mcols(x)} has multiple columns, they will all be
#'             passed through (i.e., \code{scoreCol} is ignored). To return
#'             only \code{scoreCol}, use \code{select}.}
#'         \item{select}{: Pass through only \code{scoreCol}.}
#'         \item{smooth}{: Smooth window scores (\code{minperiod} argument).}
#'         \item{smoothFuse (default)}{: Smooth window scores, identify high
#'             scoring elements (\code{thresh} argument) and fuse nearby
#'             high-scoring elements (\code{maxGap} argument).
#'         }
#'     }
#' @param minperiod Numeric scalar that defines the low-pass
#'     filter parameter used to smooth the scores for segmentation.
#'     \code{minperiod} gives the minimal period (in number of windows) for the
#'     critical frequency in the score signal that should be retained. The
#'     default value is suitable to retain signals that occur in three
#'     neighboring windows. The filtering is performed using
#'     \code{\link[signal]{filtfilt}} and thus requires the \code{signal}
#'     package to be installed.
#' @param thresh A numeric scalar giving the minimal absolute window score
#'     (after smoothing, see \code{minperiod} argument) defining a region of
#'     interest. Higher values make the region detection more stringent.
#' @param maxGap Numeric scalar giving the maximal gap between neighboring
#'     windows, in base pairs, from the end of the first to the start of the
#'     next, to be fused into a single region of interest.
#' @param verbose Logical scalar. If \code{TRUE}, report on progress.
#'
#' @author Sebastien Smallwood, Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[GenomicRanges]{GRanges}} object. For \code{scoreAction}
#'     equal to \code{"pass"} or \code{"smooth"}, the returned object has the same
#'     dimensions as the input object \code{x}. For \code{scoreAction="smoothFuse"},
#'     the returned object will only contain thresholded, fused regions.
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_1_10reads.bam",
#'                              "6mA_2_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' se <- quantifyWindowsInRegion(bamfiles = modbamfiles,
#'                               region = "chr1:6940000-6955000", modbase = "a",
#'                               BPPARAM = BiocParallel::SerialParam())
#' se$group <- c("group1", "group1", "group2", "group2")
#' gr <- getDifferentiallyModifiedWindows(se, groupCol = "group")
#' gr
#'
#' grFused <- processWindowScores(x = gr, scoreCol = "logFC", thresh = 5.0)
#' grFused
#'
#' @importFrom GenomicRanges GRanges
#' @importFrom BiocGenerics sort
#' @importFrom S4Vectors mcols mcols<- subjectHits queryHits DataFrame
#' @importFrom dplyr mutate filter group_by ungroup group_split
#' @importFrom IRanges reduce findOverlaps
#' @importFrom cli cli_abort
#' @importFrom rlang .data
#'
#' @export
processWindowScores <- function(
        x,
        scoreCol = "dirNegLog10PValue",
        scoreAction = c("smoothFuse", "smooth", "pass", "select"),
        minperiod = 3,
        thresh = 3,
        maxGap = 50,
        verbose = FALSE) {
    # check argument values
    .assertVector(x = x, type = "GRanges")
    .assertScalar(x = scoreCol, type = "character",
                  validValues = colnames(mcols(x)))
    scoreAction <- match.arg(scoreAction)
    .assertScalar(x = thresh, type = "numeric", rngExcl = c(0, Inf))
    .assertScalar(x = minperiod, type = "numeric", rngIncl = c(0, Inf))
    .assertScalar(x = maxGap, type = "numeric", rngIncl = c(0, Inf))
    .assertScalar(x = verbose, type = "logical")
    if (scoreAction %in% c("smoothFuse", "smooth")) {
        .assertPackagesAvailable(pkgs = "signal")
    }

    # do we just pass-through the input?
    if (identical(scoreAction, "pass")) {
        .message("passing-through window scores")
        gr <- x
    } else if (identical(scoreAction, "select")) {
        .message("passing-through selected window scores")
        gr <- x
        mcols(gr) <- mcols(gr)[, scoreCol, drop = FALSE]
    } else {
        # smooth scores
        .message("smoothing windows")
        xdf <- data.frame(unname(x), check.names = FALSE) |>
            mutate(chunkId = cumsum(
                c(1, (start[-1] - end[-length(x)] > maxGap |
                          seqnames[-1] != seqnames[-length(x)])))) |>
            group_by(.data$chunkId) |>
            mutate(sscore = .filterScores(.data[[scoreCol]],
                                          minperiod = minperiod,
                                          maxperiod = Inf,
                                          type = "low")) |>
            ungroup()

        if (identical(scoreAction, "smooth")) {
            gr <- x
            mcols(gr)[[scoreCol]] <- xdf$sscore

        } else if (identical(scoreAction, "smoothFuse")) {
            # threshold
            .message("thresholding smoothed scores")
            xdfSel <- xdf |>
                dplyr::filter(abs(.data$sscore) >= thresh) |>
                mutate(direction = factor(
                    ifelse(sign(.data$sscore) == -1,
                           "negative", "positive"),
                    levels = c("negative", "positive")))

            # summarise
            .message("summarise {nrow(xdfSel)} window{?s} into regions of interest")
            grL <- xdfSel |>
                group_by(.data$direction) |>
                group_split() |>
                lapply(function(x) {
                    gr1 <- as(x, "GRanges") |>
                        reduce(min.gapwidth = maxGap)
                    ov1 <- findOverlaps(query = as(x, "GRanges"),
                                        subject = gr1, type = "within")
                    mcols(gr1)[[paste0(scoreCol, "Thresh")]] <- as.vector(
                        tapply(X = x$sscore[queryHits(ov1)],
                               INDEX = subjectHits(ov1),
                               FUN = mean))
                    mcols(gr1)[["numWindowsThresh"]] <-
                        tabulate(subjectHits(ov1))
                    gr1$direction <- x$direction[1]
                    gr1
                })
            if (sum(lengths(grL)) > 0) {
                gr <- sort(sort(do.call(c, grL)), ignore.strand = TRUE)
                ov <- findOverlaps(query = x, subject = gr, type = "within")
                mcols(gr)[[scoreCol]] <- as.vector(
                    tapply(X = xdf$sscore[queryHits(ov)],
                           INDEX = subjectHits(ov),
                           FUN = mean))
                mcols(gr)[["numWindows"]] <- tabulate(subjectHits(ov))
            } else {
                gr <- GRanges()
                mcols(gr) <- DataFrame(thresh = numeric(0),
                                       numWindowsThresh = integer(0),
                                       direction = factor(character(0),
                                                          levels = c("negative",
                                                                     "positive")),
                                       score = numeric(0),
                                       numWindows = numeric(0))
                colnames(mcols(gr))[c(1,4)] <- paste0(scoreCol, c("Thresh", ""))
            }
        }
    }

    return(gr)
}

#' Scan one or more chromosomes for high-scoring regions
#'
#' Given one or several modBam files and a vector with chromosome lengths,
#' quantify the modification data in windows using \code{quantFunction},
#' calculate a score for each window using \code{scoreFunction} and fuse
#' neighboring high-scoring windows. For example, the quantification could
#' sum up observed counts in each window (implemented in \code{sumNmodNvalid}),
#' and the score could be a directional P value measuring differential
#' modification between two groups of modBam files (implemented in
#' \code{getDifferentiallyModifiedWindows}), and the identified windows would
#' then be differentially modified regions (DMRs). Please note that
#' \code{quantFunction} needs to be compatible with \code{scoreFunction}, as
#' the latter consumes the output of the former.
#'
#' @inheritParams quantifyWindowsInRegion
#' @inheritParams processWindowScores
#'
#' @param chromosomeLengths A named character vector with lengths of
#'     chromosomes to be analyzed, for example the return value of
#'     \code{seqlengths(BSgenomeObject)}.
#' @param scoreFunction A character scalar giving the name of the scoring
#'     function. This function should take as a first argument a
#'     \code{\link[SummarizedExperiment]{SummarizedExperiment}} object, as
#'     generated by \code{quantifyWindowsInRegion}. Additional arguments may
#'     be passed to \code{scoreFunction} using \code{scoreFunctionArgs}. The
#'     function must return a \code{\link[GenomicRanges]{GRanges}} object
#'     (typically corresponding to the \code{rowRanges} of the input) with the
#'     score added to the \code{mcols()}.
#' @param scoreFunctionArgs List with additional arguments for \code{scoreFunction}.
#' @param tileSize A numeric scalar giving the approximate size of a
#'     genomic region for which the data is loaded at once. Chromosomes that
#'     are larger than \code{tileSize} will be automatically split into
#'     multiple tiles. Reduce this size if you would like to reduce the memory
#'     usage of the function.
#'
#' @author Charlotte Soneson, Michael Stadler
#'
#' @returns A \code{\link[GenomicRanges]{GRanges}} object with identified
#'     regions of interest, or a named list of such objects if
#'     \code{scoreCol} is a vector of length >1.
#'
#' @examples
#' modbamfiles <- system.file("extdata",
#'                            c("6mA_1_10reads.bam", "6mA_1_10reads.bam",
#'                              "6mA_2_10reads.bam", "6mA_2_10reads.bam"),
#'                            package = "footprintR")
#' gr <- scanForHighScoringRegions(
#'     bamfiles = modbamfiles,
#'     sampleAnnot = data.frame(sample = c("s1","s2","s3","s4"),
#'                              group = c("A","A","B","B")),
#'     chromosomeLengths = c(chr1 = 6955000),
#'     modbase = "a", BPPARAM = BiocParallel::SerialParam())
#' gr
#'
#' @importFrom BiocParallel MulticoreParam
#' @importFrom GenomicRanges GRanges
#' @importFrom IRanges IRanges
#' @importFrom cli cli_abort
#' @importFrom stats setNames
#'
#' @export
scanForHighScoringRegions <- function(
        bamfiles,
        sampleAnnot,
        chromosomeLengths,
        quantFunction = "sumNmodNvalid",
        quantFunctionArgs = list(),
        scoreFunction = "getDifferentiallyModifiedWindows",
        scoreFunctionArgs = list(),
        modbase,
        level = "summary",
        modProbThreshold = 0.5,
        tileSize = 1e6,
        seqinfo = NULL,
        sequenceContextWidth = 0,
        sequenceReference = NULL,
        sequenceContext = NULL,
        windowMode = "fixed",
        windowSize = 24,
        windowStep = round(windowSize/2),
        scoreCol = "dirNegLog10PValue",
        scoreAction = "smoothFuse",
        minperiod = 3,
        thresh = 3,
        maxGap = 50,
        BPPARAM = MulticoreParam(4L, RNGseed = 42L),
        verbose = FALSE) {
    # check parameters
    .assertVector(x = chromosomeLengths, type = "numeric")
    if (is.null(names(chromosomeLengths)) ||
        any(duplicated(names(chromosomeLengths))) ||
        any(names(chromosomeLengths) == "")) {
        cli_abort("{.arg chromosomeLengths} must be a named vector")
    }
    .assertScalar(x = scoreFunction, type = "character")
    if (!exists(scoreFunction)) {
        cli_abort("{.arg scoreFunction} must be the name of an existing function")
    }
    .assertScalar(x = tileSize, type = "numeric", rngExcl = c(0, Inf))

    # loop over chromosomes
    grL <- lapply(names(chromosomeLengths), function(chr) {
        regs <- .tileChromosome(tileSize = min(tileSize, chromosomeLengths[chr]),
                                windowSize = windowSize,
                                windowStep = windowStep,
                                chromName = chr,
                                chromLength = chromosomeLengths[chr])

        # quantify windows for each tile and merge
        tileL <- lapply(seq_along(regs), function(i) {
            quantifyWindowsInRegion(bamfiles = bamfiles,
                                    region = regs[i],
                                    modbase = modbase,
                                    level = level,
                                    modProbThreshold = modProbThreshold,
                                    sampleAnnot = sampleAnnot,
                                    seqinfo = seqinfo,
                                    sequenceContextWidth = sequenceContextWidth,
                                    sequenceReference = sequenceReference,
                                    sequenceContext = sequenceContext,
                                    windowMode = windowMode,
                                    windowSize = windowSize,
                                    windowStep = windowStep,
                                    quantFunction = quantFunction,
                                    quantFunctionArgs = quantFunctionArgs,
                                    BPPARAM = BPPARAM,
                                    verbose = verbose)
        })
        se <- do.call(rbind, tileL[unlist(lapply(tileL, function(x) nrow(x) > 0))])

        # calculate window scores
        grScores <- do.call(scoreFunction, c(list(quote(se)), scoreFunctionArgs))

        # fuse windows
        grScoresFused <- lapply(setNames(scoreCol, scoreCol), function(sc) {
            processWindowScores(x = grScores,
                                scoreCol = sc,
                                scoreAction = scoreAction,
                                minperiod = minperiod,
                                thresh = thresh,
                                maxGap = maxGap,
                                verbose = verbose)
        })

        # return fused windows
        return(grScoresFused)
    })
    gr <- lapply(setNames(scoreCol, scoreCol), function(sc) {
        do.call(c, lapply(grL, "[[", sc))
    })
    if (length(scoreCol) == 1) {
        gr <- gr[[1]]
    }

    return(gr)
}
